USE [CAPINVREPOSITORY]
GO

IF ( OBJECT_ID('DBO.USP_CAPINV_UI_DATA_UPDATE', 'P') IS NOT NULL ) 
   DROP PROCEDURE DBO.USP_CAPINV_UI_DATA_UPDATE
GO

CREATE PROCEDURE [DBO].USP_CAPINV_UI_DATA_UPDATE
/****************************************************************************************************
* COPYRIGHT REVENUE ANALYTICS 2017
* ALL RIGHTS RESERVED
*
* CREATED BY: DATA ENGINEERING
* FILENAME:   USP_CAPINV_UI_DATA_UPDATE.SQL
* DATE:       09/14/2017
*
* APPLICATION:  UPDATE UI TABLES WITH RECENT DATA
*               
* PARAMETERS:   @V_PARENT_PROCESS_ID == PARENT OR CALLING PROCESS ID
*				@V_ERROR_CODE		== RETURNED ERROR CODE
*  				
* ASSUMPTIONS: TABLE AD_CAPFCST_FREESALE_UBOAT UPDATED WITH RECENT DATA
* 
* INPUTS:		ANALYTICSDATAMART.DBO.AD_CAPFCST_FREESALE_UBOAT

* OUTPUTS:		ANALYTICSDATAMART.DBO.CAPINV_UI_AGG_FREESALE_UBOAT
*				ANALYTICSDATAMART.DBO.CAPINV_UI_FREESALE_UBOAT_CURRENT
*				
* EXAMPLE CALL: DECLARE	@RETURN_VALUE INT,
*						@V_ERROR_CODE INT
*
*				EXEC	@RETURN_VALUE = [DBO].[USP_CAPINV_UI_DATA_UPDATE]
						@V_PARENT_PROCESS_ID = 0,
*						@V_ERROR_CODE = @V_ERROR_CODE OUTPUT
*****************************************************************************************************
* NOTES:
*  NAME					CREATED        LAST MOD			COMMENTS
*  DE\ELM               4/17/2017						PROCEDURE CREATED
****************************************************************************************************/
	@V_PARENT_PROCESS_ID INT
	,@V_ERROR_CODE INT OUTPUT
AS
BEGIN
	SET NOCOUNT ON 
	--DECLARE VARIABLES
	DECLARE @V_ERRORMESSAGE NVARCHAR(4000)  
	DECLARE @V_MSG  NVARCHAR(4000)
	DECLARE @V_NOTE  NVARCHAR(4000)
	DECLARE @V_ERRORSEVERITY INT  

	DECLARE @V_PROCESS_ID INT = NEXT VALUE FOR DBO.SEQ_LOG_PROCESS_ID
	DECLARE @V_PROCESS_NAME VARCHAR(255) = OBJECT_SCHEMA_NAME(@@PROCID) + '.' + OBJECT_NAME(@@PROCID)
	DECLARE @V_FIANLERROR INT
	DECLARE @V_SYSTEM_USER NVARCHAR(255) = SYSTEM_USER
	DECLARE @V_SYSTEMTIME DATETIME = GETUTCDATE()
	DECLARE @V_RECORD_CNT INT

	DECLARE @V_STEP_ID TINYINT
	DECLARE @V_STEP_NAME VARCHAR(255)
	DECLARE @V_RUNDATE DATE = CAST((SELECT MAX(RUNDATE) FROM ANALYTICSDATAMART.DBO.AD_CAPFCST_FREESALE_UBOAT  (NOLOCK)) AS DATE)

	--ASSIGN TODAYS DATE IF RUNDATE IS NULL
	SET @V_PARENT_PROCESS_ID = COALESCE(@V_PARENT_PROCESS_ID,0)

	BEGIN TRY
		--LOG PROCESS		
		EXEC DBO.USP_LOG_PROCESS @V_PROCESS_ID = @V_PROCESS_ID
							, @V_PROCESS_NAME = @V_PROCESS_NAME
							, @V_USER_NAME = @V_SYSTEM_USER
							, @V_START_DT = @V_SYSTEMTIME
							, @V_END_DT = NULL
							, @V_STATUS = 'RUNNING'
							, @V_ACTION = 1
							, @V_PARENT_PROCESS_ID = @V_PARENT_PROCESS_ID
							, @V_NOTE = 'UPDATE UI TABLES WITH RECENT DATA'
							, @V_START_STEP = 1;

		SET @V_STEP_ID = 10
		SET @V_STEP_NAME = 'BUILD TUBE MAP DATA TABLE'
		SET @V_NOTE = 'BUILD THE TUBE MAP DATA TABLE AT THE ISC=LEAD LEVEL'
		EXEC DBO.USP_LOG_PROCESS_DETAIL @V_PROCESS_ID = @V_PROCESS_ID
  					, @V_STEP_ID = @V_STEP_ID
  					, @V_STEP_NAME = @V_STEP_NAME
  					, @V_START_DT = @V_SYSTEMTIME
  					, @V_END_DT = NULL
  					, @V_STATUS = 'RUNNING'
  					, @V_ROWS_PROCESSED = NULL
  					, @V_ACTION = 1
  					, @V_NOTE = @V_NOTE;

		IF OBJECT_ID('CAPINVREPOSITORY.DBO.TMP_CAPINV_UI_AGG_FREESALE_UBOAT', 'U') IS NOT NULL
		  DROP TABLE CAPINVREPOSITORY.DBO.TMP_CAPINV_UI_AGG_FREESALE_UBOAT;

		;WITH UI_AGG_DATA AS
		(
			SELECT      [RUNID]
					   ,[RUNDATE]
					   ,[VOYAGE]
					   ,[VESSELCODE]
					   ,[SERVICECODE]
					   ,[LEGSEQID]
					   ,[SERVICECODEDIRECTION]
					   ,[DEPARTUREPORT]
					   ,[ARRIVALPORT]
					   ,[VESSELOPERATOR]
					   ,[DEPARTUREDATE]
					   ,MAX([ARRIVALDATE]) AS [ARRIVALDATE]
					   ,SUM([INTAKETEU]) AS [INTAKETEU]
					   ,SUM([INTAKETONS]) AS [INTAKETONS]
					   ,SUM([INTAKEPLUGS]) AS [INTAKEPLUGS]
					   ,SUM([ALLOCATIONTEU]) AS [ALLOCATIONTEU]
					   ,SUM([ALLOCATIONTONS]) AS [ALLOCATIONTONS]
					   ,SUM([ALLOCATIONPLUGS]) AS [ALLOCATIONPLUGS]
					   ,SUM([TOTALEMPTYTEU]) AS [TOTALEMPTYTEU]
					   ,SUM([TOTALCOMMITFILINGSTEU]) AS [TOTALCOMMITFILINGSTEU]
					   ,SUM([FREESALEALLOCATIONTEU]) AS [FREESALEALLOCATIONTEU]
					   ,SUM([OVERBOOKTEU]) AS [OVERBOOKTEU]
					   ,CAST(0 AS NUMERIC(15,4)) AS OVERBOOKPCT
					   ,SUM([FREESALE_AVAILABLETEU]) AS [FREESALE_AVAILABLETEU]
					   ,SUM([FREESALECONSUMPTIONTEU]) AS [FREESALECONSUMPTIONTEU]
					   ,SUM([FREESALEDISPLACEMENTTEU]) AS [FREESALEDISPLACEMENTTEU]
					   ,SUM([DISPLACEMENTFFE]) AS [DISPLACEMENTFFE]
					   ,SUM([CONSUMPTIONDISPLACEMENTTEU]) AS [CONSUMPTIONDISPLACEMENTTEU]
					   ,SUM([REMAINING_FREESALEDISPLACEMENTTEU]) AS [REMAINING_FREESALEDISPLACEMENTTEU]
					   ,SUM([REMAINING_FREESALETEU]) AS [REMAINING_FREESALETEU]
					   ,SUM([REMAINING_FREESALEDISPLACEMENTNOOVERBOOKTEU]) AS [REMAINING_FREESALEDISPLACEMENTNOOVERBOOKTEU]
					   ,SUM([REMAINING_FREESALENOOVERBOOKTEU]) AS [REMAINING_FREESALENOOVERBOOKTEU]
					   ,SUM([REMAINING_FREESALEDISPLACEMENTFFE]) AS [REMAINING_FREESALEDISPLACEMENTFFE]
					   ,SUM([REMAINING_FREESALEFFE]) AS [REMAINING_FREESALEFFE]
					   ,SUM([TOTALEMPTYTONS]) AS [TOTALEMPTYTONS]
					   ,SUM([TOTALCOMMITFILINGSTONS]) AS [TOTALCOMMITFILINGSTONS]
					   ,SUM([FREESALEALLOCATIONTONS]) AS [FREESALEALLOCATIONTONS]
					   ,SUM([OVERBOOKTONS]) AS [OVERBOOKTONS]
					   ,SUM([FREESALE_AVAILABLETONS]) AS [FREESALE_AVAILABLETONS]
					   ,SUM([FREESALE_AVAILABLENOOVERBOOKTONS]) AS [FREESALE_AVAILABLENOOVERBOOKTONS]
					   ,SUM([FREESALECONSUMPTIONTONS]) AS [FREESALECONSUMPTIONTONS]
					   ,SUM([REMAINING_FREESALETONS]) AS [REMAINING_FREESALETONS]
					   ,SUM([REMAINING_FREESALENOOVERBOOKTONS]) AS [REMAINING_FREESALENOOVERBOOKTONS]
					   ,SUM([TOTALCOMMITFILINGSPLUGS]) AS [TOTALCOMMITFILINGSPLUGS]
					   ,SUM([FREESALEALLOCATIONPLUGS]) AS [FREESALEALLOCATIONPLUGS]
					   ,SUM([OVERBOOKPLUGS]) AS [OVERBOOKPLUGS]
					   ,SUM([FREESALE_AVAILABLEPLUGS]) AS [FREESALE_AVAILABLEPLUGS]
					   ,SUM([FREESALE_AVAILABLENOOVERBOOKPLUGS]) AS [FREESALE_AVAILABLENOOVERBOOKPLUGS]
					   ,SUM([FREESALECONSUMPTIONPLUGS]) AS [FREESALECONSUMPTIONPLUGS]
					   ,SUM([REMAINING_FREESALEPLUGS]) AS [REMAINING_FREESALEPLUGS]
					   ,SUM([REMAINING_FREESALENOOVERBOOKPLUGS]) AS [REMAINING_FREESALENOOVERBOOKPLUGS]
					   ,CAST('LEAD' AS VARCHAR(10)) AS [ISC]
			FROM ANALYTICSDATAMART.DBO.AD_CAPFCST_FREESALE_UBOAT (NOLOCK)
			WHERE RUNDATE BETWEEN DATEADD(DAY,-3,@V_RUNDATE) AND @V_RUNDATE
			GROUP BY [RUNID]
					   ,[RUNDATE]
					   ,[VOYAGE]
					   ,[VESSELCODE]
					   ,[SERVICECODE]
					   ,[LEGSEQID]
					   ,[SERVICECODEDIRECTION]
					   ,[DEPARTUREPORT]
					   ,[ARRIVALPORT]
					   ,[VESSELOPERATOR]
					   ,[DEPARTUREDATE]
		),
		SUMDATA AS
		(
			SELECT ROW_NUMBER() OVER(ORDER BY VOYAGE) AS ID
					   ,[RUNID]
					   ,[RUNDATE]
					   ,[VOYAGE]
					   ,[VESSELCODE]
					   ,[SERVICECODE]
					   ,[LEGSEQID]
					   ,[SERVICECODEDIRECTION]
					   ,[DEPARTUREPORT]
					   ,[ARRIVALPORT]
					   ,[VESSELOPERATOR]
					   ,[DEPARTUREDATE]
					   ,[ARRIVALDATE]
					   ,[INTAKETEU]
					   ,[INTAKETONS]
					   ,[INTAKEPLUGS]
					   ,[ALLOCATIONTEU]
					   ,[ALLOCATIONTONS]
					   ,[ALLOCATIONPLUGS]
					   ,[TOTALEMPTYTEU]
					   ,[TOTALCOMMITFILINGSTEU]
					   ,[FREESALEALLOCATIONTEU]
					   ,[OVERBOOKTEU]
					   ,OVERBOOKPCT
					   ,[FREESALE_AVAILABLETEU]
					   ,[FREESALECONSUMPTIONTEU]
					   ,[FREESALEDISPLACEMENTTEU]
					   ,[DISPLACEMENTFFE]
					   ,[CONSUMPTIONDISPLACEMENTTEU]
					   ,[REMAINING_FREESALEDISPLACEMENTTEU]
					   ,[REMAINING_FREESALETEU]
					   ,[REMAINING_FREESALEDISPLACEMENTNOOVERBOOKTEU]
					   ,[REMAINING_FREESALENOOVERBOOKTEU]
					   ,[REMAINING_FREESALEDISPLACEMENTFFE]
					   ,[REMAINING_FREESALEFFE]
					   ,[TOTALEMPTYTONS]
					   ,[TOTALCOMMITFILINGSTONS]
					   ,[FREESALEALLOCATIONTONS]
					   ,[OVERBOOKTONS]
					   ,[FREESALE_AVAILABLETONS]
					   ,[FREESALE_AVAILABLENOOVERBOOKTONS]
					   ,[FREESALECONSUMPTIONTONS]
					   ,[REMAINING_FREESALETONS]
					   ,[REMAINING_FREESALENOOVERBOOKTONS]
					   ,[TOTALCOMMITFILINGSPLUGS]
					   ,[FREESALEALLOCATIONPLUGS]
					   ,[OVERBOOKPLUGS]
					   ,[FREESALE_AVAILABLEPLUGS]
					   ,[FREESALE_AVAILABLENOOVERBOOKPLUGS]
					   ,[FREESALECONSUMPTIONPLUGS]
					   ,[REMAINING_FREESALEPLUGS]
					   ,[REMAINING_FREESALENOOVERBOOKPLUGS]
					   ,[ISC]
				FROM UI_AGG_DATA
		)
		SELECT
				   A.ID, A.RUNID, A.RUNDATE, A.VESSELCODE AS VESSEL,A.VOYAGE, A.SERVICECODE AS SERVICE, A.SERVICECODEDIRECTION AS [SERVICE CODE DIRECTION],
				LEFT(A.DEPARTUREPORT, 5) AS [DEPARTURE PORTCALL],PC1.SITENAME AS [DEPARTURE PORTCITY], LEFT(A.ARRIVALPORT, 5) AS [ARRIVAL PORTCALL],PC2.SITENAME AS [ARRIVAL PORTCITY],
					  A.LEGSEQID, CAST(A.DEPARTUREDATE AS DATE) AS DEPARTURE, DT.INT_YEARWEEK AS WEEK_OF_YEAR,
				CAST(A.ARRIVALDATE AS DATE) AS ARRIVAL, A.ALLOCATIONTEU AS [MSK ALLOCATION TEU], A.ALLOCATIONTONS AS [MSK ALLOCATION MTS],
				A.ALLOCATIONPLUGS AS [MSK ALLOCATION PLUGS], CAST(ROUND(A.TOTALEMPTYTEU, 0) AS INT) AS [EMPTY ALLOCATION TEU], CAST(ROUND(A.TOTALEMPTYTONS, 0) AS INT)
				AS [EMPTY ALLOCATION MTS], CAST(A.TOTALCOMMITFILINGSTEU AS INT) AS [COMMITMENT ALLOCATION TEU], CAST(ROUND(A.TOTALCOMMITFILINGSTONS, 0) AS INT)
				AS [COMMITMENT ALLOCATION MTS], CAST(A.TOTALCOMMITFILINGSPLUGS AS INT) AS [COMMITMENT ALLOCATION PLUGS], CAST(A.TOTALCOMMITFILINGSTEU AS INT)
				AS [COMMITMENT CONSUMPTION TEU], CAST(ROUND(A.TOTALCOMMITFILINGSTONS, 0) AS INT) AS [COMMITMENT CONSUMPTION MTS], CAST(A.TOTALCOMMITFILINGSPLUGS AS INT)
				AS [COMMITMENT CONSUMPTION PLUGS], CAST(A.FREESALEALLOCATIONTEU AS INT) AS [FREESALE AVAILABLE TEU - BEFORE OVERBOOKING],
				CAST(ROUND(A.FREESALE_AVAILABLENOOVERBOOKTONS, 0) AS INT) AS [FREESALE AVAILABLE MTS - BEFORE OVERBOOKING], CAST(A.FREESALE_AVAILABLENOOVERBOOKPLUGS AS INT)
				AS [FREESALE AVAILABLE PLUGS - BEFORE OVERBOOKING], CAST(A.FREESALE_AVAILABLETEU AS INT) AS [FREESALE AVAILABLE TEU - INCL.  OVERBOOKING],
				CAST(ROUND(A.FREESALE_AVAILABLETONS, 0) AS INT) AS [FREESALE AVAILABLE MTS - INCL.  OVERBOOKING], CAST(A.FREESALE_AVAILABLEPLUGS AS INT)
				AS [FREESALE AVAILABLE PLUGS - INCL.  OVERBOOKING], CAST(A.FREESALECONSUMPTIONTEU AS INT) AS [FREESALE CONSUMPTION TEU], CAST(A.FREESALEDISPLACEMENTTEU AS INT)
				AS [OOG DISPLACEMENT TEU], CAST(A.CONSUMPTIONDISPLACEMENTTEU AS INT) AS [FREESALE CONSUMPTION AND DISPLACEMENT TEU TOTAL],
				CAST(ROUND(A.FREESALECONSUMPTIONTONS, 0) AS INT) AS [FREESALE CONSUMPTION MTS], CAST(A.FREESALECONSUMPTIONPLUGS AS INT) AS [FREESALE CONSUMPTION PLUGS],
				CAST(A.REMAINING_FREESALETEU AS INT) AS [REMAINING CAPACITY TEU - BEFORE OOG DISPLACEMENT], CAST(A.REMAINING_FREESALEDISPLACEMENTTEU AS INT)
				AS [REMAINING CAPACITY TEU - INCL. OOG DISPLACEMENT], CAST(ROUND(A.REMAINING_FREESALETONS, 0) AS INT) AS [REMAINING CAPACITY MTS],
				CAST(A.REMAINING_FREESALEPLUGS AS INT) AS [REMAINING CAPACITY PLUGS], ISC AS [ISC INDICATOR (LEAD TRADE / ISC1)],
				SVC.SERVICENAME, VSL.VESSELNAME
		INTO CAPINVREPOSITORY.DBO.TMP_CAPINV_UI_AGG_FREESALE_UBOAT 
		FROM   SUMDATA A
			   INNER JOIN  ANALYTICSDATAMART.DBO.DIM_DATE AS DT (NOLOCK)
		ON
			   CAST(A.DEPARTUREDATE AS DATE) = CAST(DT.DATE AS DATE)
		INNER JOIN ANALYTICSDATAMART.DBO.DIM_SERVICE SVC (NOLOCK)
		ON
			   A.SERVICECODE = SVC.SERVICECD
		LEFT OUTER JOIN ANALYTICSDATAMART.DBO.VWVESSELS VSL
		ON
			   A.VESSELCODE = VSL.VESSELCODE
		LEFT OUTER JOIN ANALYTICSDATAMART.DBO.VWPORTCITIES PC1
		ON
			   A.DEPARTUREPORT = PC1.SITE_CD
		LEFT OUTER JOIN ANALYTICSDATAMART.DBO.VWPORTCITIES PC2
		ON
			   A.ARRIVALPORT = PC2.SITE_CD
		WHERE
			   LEFT(A.DEPARTUREPORT, 5) <> LEFT(A.ARRIVALPORT,5) AND A.SERVICECODEDIRECTION IS NOT NULL
		OPTION (MAXDOP 8);

		SET @V_RECORD_CNT = @@ROWCOUNT
		SET @V_SYSTEMTIME = SYSDATETIME()

		--	LOG PROCESS DETAIL
		SET @V_NOTE = @V_STEP_NAME + ' COMPLETED SUCCESSFULLY'
		EXEC DBO.USP_LOG_PROCESS_DETAIL @V_PROCESS_ID = @V_PROCESS_ID
  					, @V_STEP_ID = @V_STEP_ID
  					, @V_STEP_NAME = @V_STEP_NAME
  					, @V_START_DT = NULL
  					, @V_END_DT = @V_SYSTEMTIME
  					, @V_STATUS = 'COMPLETED'
  					, @V_ROWS_PROCESSED = @V_RECORD_CNT
  					, @V_ACTION = 2
  					, @V_NOTE = @V_NOTE;

		SET @V_STEP_ID = 15
		SET @V_STEP_NAME = 'REFRESH TUBE MAP DATA TABLE'
		SET @V_NOTE = 'REFRESH THE TUBE MAP DATA TABLE AT THE ISC=LEAD LEVEL'
		EXEC DBO.USP_LOG_PROCESS_DETAIL @V_PROCESS_ID = @V_PROCESS_ID
  					, @V_STEP_ID = @V_STEP_ID
  					, @V_STEP_NAME = @V_STEP_NAME
  					, @V_START_DT = @V_SYSTEMTIME
  					, @V_END_DT = NULL
  					, @V_STATUS = 'RUNNING'
  					, @V_ROWS_PROCESSED = NULL
  					, @V_ACTION = 1
  					, @V_NOTE = @V_NOTE;

			TRUNCATE TABLE ANALYTICSDATAMART.[DBO].[CAPINV_UI_AGG_FREESALE_UBOAT];

			INSERT INTO ANALYTICSDATAMART.[DBO].[CAPINV_UI_AGG_FREESALE_UBOAT]
					   ([ID]
					   ,[RUNID]
					   ,[RUNDATE]
					   ,[VESSEL]
					   ,[VOYAGE]
					   ,[SERVICE]
					   ,[SERVICE CODE DIRECTION]
					   ,[DEPARTURE PORTCALL]
					   ,[DEPARTURE PORTCITY]
					   ,[ARRIVAL PORTCALL]
					   ,[ARRIVAL PORTCITY]
					   ,[LEGSEQID]
					   ,[DEPARTURE]
					   ,[WEEK_OF_YEAR]
					   ,[ARRIVAL]
					   ,[MSK ALLOCATION TEU]
					   ,[MSK ALLOCATION MTS]
					   ,[MSK ALLOCATION PLUGS]
					   ,[EMPTY ALLOCATION TEU]
					   ,[EMPTY ALLOCATION MTS]
					   ,[COMMITMENT ALLOCATION TEU]
					   ,[COMMITMENT ALLOCATION MTS]
					   ,[COMMITMENT ALLOCATION PLUGS]
					   ,[COMMITMENT CONSUMPTION TEU]
					   ,[COMMITMENT CONSUMPTION MTS]
					   ,[COMMITMENT CONSUMPTION PLUGS]
					   ,[FREESALE AVAILABLE TEU - BEFORE OVERBOOKING]
					   ,[FREESALE AVAILABLE MTS - BEFORE OVERBOOKING]
					   ,[FREESALE AVAILABLE PLUGS - BEFORE OVERBOOKING]
					   ,[FREESALE AVAILABLE TEU - INCL.  OVERBOOKING]
					   ,[FREESALE AVAILABLE MTS - INCL.  OVERBOOKING]
					   ,[FREESALE AVAILABLE PLUGS - INCL.  OVERBOOKING]
					   ,[FREESALE CONSUMPTION TEU]
					   ,[OOG DISPLACEMENT TEU]
					   ,[FREESALE CONSUMPTION AND DISPLACEMENT TEU TOTAL]
					   ,[FREESALE CONSUMPTION MTS]
					   ,[FREESALE CONSUMPTION PLUGS]
					   ,[REMAINING CAPACITY TEU - BEFORE OOG DISPLACEMENT]
					   ,[REMAINING CAPACITY TEU - INCL. OOG DISPLACEMENT]
					   ,[REMAINING CAPACITY MTS]
					   ,[REMAINING CAPACITY PLUGS]
					   ,[ISC INDICATOR (LEAD TRADE / ISC1)]
					   ,[SERVICENAME]
					   ,[VESSELNAME])
			SELECT		[ID]
					   ,[RUNID]
					   ,[RUNDATE]
					   ,[VESSEL]
					   ,[VOYAGE]
					   ,[SERVICE]
					   ,[SERVICE CODE DIRECTION]
					   ,[DEPARTURE PORTCALL]
					   ,[DEPARTURE PORTCITY]
					   ,[ARRIVAL PORTCALL]
					   ,[ARRIVAL PORTCITY]
					   ,[LEGSEQID]
					   ,[DEPARTURE]
					   ,[WEEK_OF_YEAR]
					   ,[ARRIVAL]
					   ,[MSK ALLOCATION TEU]
					   ,[MSK ALLOCATION MTS]
					   ,[MSK ALLOCATION PLUGS]
					   ,[EMPTY ALLOCATION TEU]
					   ,[EMPTY ALLOCATION MTS]
					   ,[COMMITMENT ALLOCATION TEU]
					   ,[COMMITMENT ALLOCATION MTS]
					   ,[COMMITMENT ALLOCATION PLUGS]
					   ,[COMMITMENT CONSUMPTION TEU]
					   ,[COMMITMENT CONSUMPTION MTS]
					   ,[COMMITMENT CONSUMPTION PLUGS]
					   ,[FREESALE AVAILABLE TEU - BEFORE OVERBOOKING]
					   ,[FREESALE AVAILABLE MTS - BEFORE OVERBOOKING]
					   ,[FREESALE AVAILABLE PLUGS - BEFORE OVERBOOKING]
					   ,[FREESALE AVAILABLE TEU - INCL.  OVERBOOKING]
					   ,[FREESALE AVAILABLE MTS - INCL.  OVERBOOKING]
					   ,[FREESALE AVAILABLE PLUGS - INCL.  OVERBOOKING]
					   ,[FREESALE CONSUMPTION TEU]
					   ,[OOG DISPLACEMENT TEU]
					   ,[FREESALE CONSUMPTION AND DISPLACEMENT TEU TOTAL]
					   ,[FREESALE CONSUMPTION MTS]
					   ,[FREESALE CONSUMPTION PLUGS]
					   ,[REMAINING CAPACITY TEU - BEFORE OOG DISPLACEMENT]
					   ,[REMAINING CAPACITY TEU - INCL. OOG DISPLACEMENT]
					   ,[REMAINING CAPACITY MTS]
					   ,[REMAINING CAPACITY PLUGS]
					   ,[ISC INDICATOR (LEAD TRADE / ISC1)]
					   ,[SERVICENAME]
					   ,[VESSELNAME]
		FROM CAPINVREPOSITORY.DBO.TMP_CAPINV_UI_AGG_FREESALE_UBOAT (NOLOCK)
		OPTION (MAXDOP 8);

		SET @V_RECORD_CNT = @@ROWCOUNT
		SET @V_SYSTEMTIME = SYSDATETIME()

		--	LOG PROCESS DETAIL
		SET @V_NOTE = @V_STEP_NAME + ' COMPLETED SUCCESSFULLY'
		EXEC DBO.USP_LOG_PROCESS_DETAIL @V_PROCESS_ID = @V_PROCESS_ID
  					, @V_STEP_ID = @V_STEP_ID
  					, @V_STEP_NAME = @V_STEP_NAME
  					, @V_START_DT = NULL
  					, @V_END_DT = @V_SYSTEMTIME
  					, @V_STATUS = 'COMPLETED'
  					, @V_ROWS_PROCESSED = @V_RECORD_CNT
  					, @V_ACTION = 2
  					, @V_NOTE = @V_NOTE;

		SET @V_STEP_ID = 20
		SET @V_STEP_NAME = 'BUILD UI ISC LEVEL DATA TABLE'
		SET @V_NOTE = 'BUILD THE ISC LEVEL DATA TABLE AT THE ISC LEVEL WITH MOST RECNT RUN DATA'
		EXEC DBO.USP_LOG_PROCESS_DETAIL @V_PROCESS_ID = @V_PROCESS_ID
  					, @V_STEP_ID = @V_STEP_ID
  					, @V_STEP_NAME = @V_STEP_NAME
  					, @V_START_DT = @V_SYSTEMTIME
  					, @V_END_DT = NULL
  					, @V_STATUS = 'RUNNING'
  					, @V_ROWS_PROCESSED = NULL
  					, @V_ACTION = 1
  					, @V_NOTE = @V_NOTE;

		IF OBJECT_ID('CAPINVREPOSITORY.DBO.TMP_CAPINV_UI_FREESALE_UBOAT_CURRENT', 'U') IS NOT NULL
		  DROP TABLE CAPINVREPOSITORY.DBO.TMP_CAPINV_UI_FREESALE_UBOAT_CURRENT;

		WITH AGG_DATA AS 
		(
			SELECT ID
					   ,[RUNID]
					   ,[RUNDATE]
					   ,[VOYAGE]
					   ,[VESSELCODE]
					   ,[SERVICECODE]
					   ,[LEGSEQID]
					   ,[SERVICECODEDIRECTION]
					   ,[DEPARTUREPORT]
					   ,[ARRIVALPORT]
					   ,[VESSELOPERATOR]
					   ,[DEPARTUREDATE]
					   ,[ARRIVALDATE]
					   ,[INTAKETEU]
					   ,[INTAKETONS]
					   ,[INTAKEPLUGS]
					   ,[ALLOCATIONTEU]
					   ,[ALLOCATIONTONS]
					   ,[ALLOCATIONPLUGS]
					   ,[TOTALEMPTYTEU]
					   ,[TOTALCOMMITFILINGSTEU]
					   ,[FREESALEALLOCATIONTEU]
					   ,[OVERBOOKTEU]
					   ,OVERBOOKPCT
					   ,[FREESALE_AVAILABLETEU]
					   ,[FREESALECONSUMPTIONTEU]
					   ,[FREESALEDISPLACEMENTTEU]
					   ,[DISPLACEMENTFFE]
					   ,[CONSUMPTIONDISPLACEMENTTEU]
					   ,[REMAINING_FREESALEDISPLACEMENTTEU]
					   ,[REMAINING_FREESALETEU]
					   ,[REMAINING_FREESALEDISPLACEMENTNOOVERBOOKTEU]
					   ,[REMAINING_FREESALENOOVERBOOKTEU]
					   ,[REMAINING_FREESALEDISPLACEMENTFFE]
					   ,[REMAINING_FREESALEFFE]
					   ,[TOTALEMPTYTONS]
					   ,[TOTALCOMMITFILINGSTONS]
					   ,[FREESALEALLOCATIONTONS]
					   ,[OVERBOOKTONS]
					   ,[FREESALE_AVAILABLETONS]
					   ,[FREESALE_AVAILABLENOOVERBOOKTONS]
					   ,[FREESALECONSUMPTIONTONS]
					   ,[REMAINING_FREESALETONS]
					   ,[REMAINING_FREESALENOOVERBOOKTONS]
					   ,[TOTALCOMMITFILINGSPLUGS]
					   ,[FREESALEALLOCATIONPLUGS]
					   ,[OVERBOOKPLUGS]
					   ,[FREESALE_AVAILABLEPLUGS]
					   ,[FREESALE_AVAILABLENOOVERBOOKPLUGS]
					   ,[FREESALECONSUMPTIONPLUGS]
					   ,[REMAINING_FREESALEPLUGS]
					   ,[REMAINING_FREESALENOOVERBOOKPLUGS]
					   ,[ISC]
			FROM ANALYTICSDATAMART.DBO.AD_CAPFCST_FREESALE_UBOAT (NOLOCK)
			WHERE RUNDATE = @V_RUNDATE
		)
		SELECT
				   A.ID, A.RUNID, A.RUNDATE, A.VESSELCODE AS VESSEL,A.VOYAGE, A.SERVICECODE AS SERVICE, A.SERVICECODEDIRECTION AS [SERVICE CODE DIRECTION],
				LEFT(A.DEPARTUREPORT, 5) AS [DEPARTURE PORTCALL],PC1.SITENAME AS [DEPARTURE PORTCITY], LEFT(A.ARRIVALPORT, 5) AS [ARRIVAL PORTCALL],PC2.SITENAME AS [ARRIVAL PORTCITY],
					  A.LEGSEQID, CAST(A.DEPARTUREDATE AS DATE) AS DEPARTURE, DT.INT_YEARWEEK AS WEEK_OF_YEAR,
				CAST(A.ARRIVALDATE AS DATE) AS ARRIVAL, A.ALLOCATIONTEU AS [MSK ALLOCATION TEU], A.ALLOCATIONTONS AS [MSK ALLOCATION MTS],
				A.ALLOCATIONPLUGS AS [MSK ALLOCATION PLUGS], CAST(ROUND(A.TOTALEMPTYTEU, 0) AS INT) AS [EMPTY ALLOCATION TEU], CAST(ROUND(A.TOTALEMPTYTONS, 0) AS INT)
				AS [EMPTY ALLOCATION MTS], CAST(A.TOTALCOMMITFILINGSTEU AS INT) AS [COMMITMENT ALLOCATION TEU], CAST(ROUND(A.TOTALCOMMITFILINGSTONS, 0) AS INT)
				AS [COMMITMENT ALLOCATION MTS], CAST(A.TOTALCOMMITFILINGSPLUGS AS INT) AS [COMMITMENT ALLOCATION PLUGS], CAST(A.TOTALCOMMITFILINGSTEU AS INT)
				AS [COMMITMENT CONSUMPTION TEU], CAST(ROUND(A.TOTALCOMMITFILINGSTONS, 0) AS INT) AS [COMMITMENT CONSUMPTION MTS], CAST(A.TOTALCOMMITFILINGSPLUGS AS INT)
				AS [COMMITMENT CONSUMPTION PLUGS], CAST(A.FREESALEALLOCATIONTEU AS INT) AS [FREESALE AVAILABLE TEU - BEFORE OVERBOOKING],
				CAST(ROUND(A.FREESALE_AVAILABLENOOVERBOOKTONS, 0) AS INT) AS [FREESALE AVAILABLE MTS - BEFORE OVERBOOKING], CAST(A.FREESALE_AVAILABLENOOVERBOOKPLUGS AS INT)
				AS [FREESALE AVAILABLE PLUGS - BEFORE OVERBOOKING], CAST(A.FREESALE_AVAILABLETEU AS INT) AS [FREESALE AVAILABLE TEU - INCL.  OVERBOOKING],
				CAST(ROUND(A.FREESALE_AVAILABLETONS, 0) AS INT) AS [FREESALE AVAILABLE MTS - INCL.  OVERBOOKING], CAST(A.FREESALE_AVAILABLEPLUGS AS INT)
				AS [FREESALE AVAILABLE PLUGS - INCL.  OVERBOOKING], CAST(A.FREESALECONSUMPTIONTEU AS INT) AS [FREESALE CONSUMPTION TEU], CAST(A.FREESALEDISPLACEMENTTEU AS INT)
				AS [OOG DISPLACEMENT TEU], CAST(A.CONSUMPTIONDISPLACEMENTTEU AS INT) AS [FREESALE CONSUMPTION AND DISPLACEMENT TEU TOTAL],
				CAST(ROUND(A.FREESALECONSUMPTIONTONS, 0) AS INT) AS [FREESALE CONSUMPTION MTS], CAST(A.FREESALECONSUMPTIONPLUGS AS INT) AS [FREESALE CONSUMPTION PLUGS],
				CAST(A.REMAINING_FREESALETEU AS INT) AS [REMAINING CAPACITY TEU - BEFORE OOG DISPLACEMENT], CAST(A.REMAINING_FREESALEDISPLACEMENTTEU AS INT)
				AS [REMAINING CAPACITY TEU - INCL. OOG DISPLACEMENT], CAST(ROUND(A.REMAINING_FREESALETONS, 0) AS INT) AS [REMAINING CAPACITY MTS],
				CAST(A.REMAINING_FREESALEPLUGS AS INT) AS [REMAINING CAPACITY PLUGS], ISC AS [ISC INDICATOR (LEAD TRADE / ISC1)],
				SVC.SERVICENAME, VSL.VESSELNAME
		INTO CAPINVREPOSITORY.DBO.TMP_CAPINV_UI_FREESALE_UBOAT_CURRENT
		FROM          
			   AGG_DATA A
			   INNER JOIN  ANALYTICSDATAMART.DBO.DIM_DATE AS DT (NOLOCK)
		ON
			   CAST(A.DEPARTUREDATE AS DATE) = CAST(DT.DATE AS DATE)
		INNER JOIN ANALYTICSDATAMART.DBO.DIM_SERVICE SVC (NOLOCK)
		ON
			   A.SERVICECODE = SVC.SERVICECD
		LEFT OUTER JOIN ANALYTICSDATAMART.DBO.VWVESSELS VSL
		ON
			   A.VESSELCODE = VSL.VESSELCODE
		LEFT OUTER JOIN ANALYTICSDATAMART.DBO.VWPORTCITIES PC1
		ON
			   A.DEPARTUREPORT = PC1.SITE_CD
		LEFT OUTER JOIN ANALYTICSDATAMART.DBO.VWPORTCITIES PC2
		ON
			   A.ARRIVALPORT = PC2.SITE_CD
		WHERE
			   LEFT(A.DEPARTUREPORT, 5) <> LEFT(A.ARRIVALPORT,5) AND A.SERVICECODEDIRECTION IS NOT NULL
		OPTION (MAXDOP 8);

		SET @V_RECORD_CNT = @@ROWCOUNT
		SET @V_SYSTEMTIME = SYSDATETIME()

		--	LOG PROCESS DETAIL
		SET @V_NOTE = @V_STEP_NAME + ' COMPLETED SUCCESSFULLY'
		EXEC DBO.USP_LOG_PROCESS_DETAIL @V_PROCESS_ID = @V_PROCESS_ID
  					, @V_STEP_ID = @V_STEP_ID
  					, @V_STEP_NAME = @V_STEP_NAME
  					, @V_START_DT = NULL
  					, @V_END_DT = @V_SYSTEMTIME
  					, @V_STATUS = 'COMPLETED'
  					, @V_ROWS_PROCESSED = @V_RECORD_CNT
  					, @V_ACTION = 2
  					, @V_NOTE = @V_NOTE;


		SET @V_STEP_ID = 25
		SET @V_STEP_NAME = 'REFRESH UI ISC LEVEL DATA TABLE'
		SET @V_NOTE = 'REFRESH THE ISC LEVEL DATA TABLE AT THE ISC LEVEL WITH MOST RECNT RUN DATA'
		EXEC DBO.USP_LOG_PROCESS_DETAIL @V_PROCESS_ID = @V_PROCESS_ID
  					, @V_STEP_ID = @V_STEP_ID
  					, @V_STEP_NAME = @V_STEP_NAME
  					, @V_START_DT = @V_SYSTEMTIME
  					, @V_END_DT = NULL
  					, @V_STATUS = 'RUNNING'
  					, @V_ROWS_PROCESSED = NULL
  					, @V_ACTION = 1
  					, @V_NOTE = @V_NOTE;

			TRUNCATE TABLE ANALYTICSDATAMART.[DBO].CAPINV_UI_FREESALE_UBOAT_CURRENT;

			INSERT INTO ANALYTICSDATAMART.[DBO].CAPINV_UI_FREESALE_UBOAT_CURRENT
					   ([ID]
					   ,[RUNID]
					   ,[RUNDATE]
					   ,[VESSEL]
					   ,[VOYAGE]
					   ,[SERVICE]
					   ,[SERVICE CODE DIRECTION]
					   ,[DEPARTURE PORTCALL]
					   ,[DEPARTURE PORTCITY]
					   ,[ARRIVAL PORTCALL]
					   ,[ARRIVAL PORTCITY]
					   ,[LEGSEQID]
					   ,[DEPARTURE]
					   ,[WEEK_OF_YEAR]
					   ,[ARRIVAL]
					   ,[MSK ALLOCATION TEU]
					   ,[MSK ALLOCATION MTS]
					   ,[MSK ALLOCATION PLUGS]
					   ,[EMPTY ALLOCATION TEU]
					   ,[EMPTY ALLOCATION MTS]
					   ,[COMMITMENT ALLOCATION TEU]
					   ,[COMMITMENT ALLOCATION MTS]
					   ,[COMMITMENT ALLOCATION PLUGS]
					   ,[COMMITMENT CONSUMPTION TEU]
					   ,[COMMITMENT CONSUMPTION MTS]
					   ,[COMMITMENT CONSUMPTION PLUGS]
					   ,[FREESALE AVAILABLE TEU - BEFORE OVERBOOKING]
					   ,[FREESALE AVAILABLE MTS - BEFORE OVERBOOKING]
					   ,[FREESALE AVAILABLE PLUGS - BEFORE OVERBOOKING]
					   ,[FREESALE AVAILABLE TEU - INCL.  OVERBOOKING]
					   ,[FREESALE AVAILABLE MTS - INCL.  OVERBOOKING]
					   ,[FREESALE AVAILABLE PLUGS - INCL.  OVERBOOKING]
					   ,[FREESALE CONSUMPTION TEU]
					   ,[OOG DISPLACEMENT TEU]
					   ,[FREESALE CONSUMPTION AND DISPLACEMENT TEU TOTAL]
					   ,[FREESALE CONSUMPTION MTS]
					   ,[FREESALE CONSUMPTION PLUGS]
					   ,[REMAINING CAPACITY TEU - BEFORE OOG DISPLACEMENT]
					   ,[REMAINING CAPACITY TEU - INCL. OOG DISPLACEMENT]
					   ,[REMAINING CAPACITY MTS]
					   ,[REMAINING CAPACITY PLUGS]
					   ,[ISC INDICATOR (LEAD TRADE / ISC1)]
					   ,[SERVICENAME]
					   ,[VESSELNAME])
			SELECT  [ID]
					   ,[RUNID]
					   ,[RUNDATE]
					   ,[VESSEL]
					   ,[VOYAGE]
					   ,[SERVICE]
					   ,[SERVICE CODE DIRECTION]
					   ,[DEPARTURE PORTCALL]
					   ,[DEPARTURE PORTCITY]
					   ,[ARRIVAL PORTCALL]
					   ,[ARRIVAL PORTCITY]
					   ,[LEGSEQID]
					   ,[DEPARTURE]
					   ,[WEEK_OF_YEAR]
					   ,[ARRIVAL]
					   ,[MSK ALLOCATION TEU]
					   ,[MSK ALLOCATION MTS]
					   ,[MSK ALLOCATION PLUGS]
					   ,[EMPTY ALLOCATION TEU]
					   ,[EMPTY ALLOCATION MTS]
					   ,[COMMITMENT ALLOCATION TEU]
					   ,[COMMITMENT ALLOCATION MTS]
					   ,[COMMITMENT ALLOCATION PLUGS]
					   ,[COMMITMENT CONSUMPTION TEU]
					   ,[COMMITMENT CONSUMPTION MTS]
					   ,[COMMITMENT CONSUMPTION PLUGS]
					   ,[FREESALE AVAILABLE TEU - BEFORE OVERBOOKING]
					   ,[FREESALE AVAILABLE MTS - BEFORE OVERBOOKING]
					   ,[FREESALE AVAILABLE PLUGS - BEFORE OVERBOOKING]
					   ,[FREESALE AVAILABLE TEU - INCL.  OVERBOOKING]
					   ,[FREESALE AVAILABLE MTS - INCL.  OVERBOOKING]
					   ,[FREESALE AVAILABLE PLUGS - INCL.  OVERBOOKING]
					   ,[FREESALE CONSUMPTION TEU]
					   ,[OOG DISPLACEMENT TEU]
					   ,[FREESALE CONSUMPTION AND DISPLACEMENT TEU TOTAL]
					   ,[FREESALE CONSUMPTION MTS]
					   ,[FREESALE CONSUMPTION PLUGS]
					   ,[REMAINING CAPACITY TEU - BEFORE OOG DISPLACEMENT]
					   ,[REMAINING CAPACITY TEU - INCL. OOG DISPLACEMENT]
					   ,[REMAINING CAPACITY MTS]
					   ,[REMAINING CAPACITY PLUGS]
					   ,[ISC INDICATOR (LEAD TRADE / ISC1)]
					   ,[SERVICENAME]
					   ,[VESSELNAME]
		FROM CAPINVREPOSITORY.DBO.TMP_CAPINV_UI_FREESALE_UBOAT_CURRENT (NOLOCK)
		OPTION (MAXDOP 8);

		SET @V_RECORD_CNT = @@ROWCOUNT
		SET @V_SYSTEMTIME = SYSDATETIME()

		--	LOG PROCESS DETAIL
		SET @V_NOTE = @V_STEP_NAME + ' COMPLETED SUCCESSFULLY'
		EXEC DBO.USP_LOG_PROCESS_DETAIL @V_PROCESS_ID = @V_PROCESS_ID
  					, @V_STEP_ID = @V_STEP_ID
  					, @V_STEP_NAME = @V_STEP_NAME
  					, @V_START_DT = NULL
  					, @V_END_DT = @V_SYSTEMTIME
  					, @V_STATUS = 'COMPLETED'
  					, @V_ROWS_PROCESSED = @V_RECORD_CNT
  					, @V_ACTION = 2
  					, @V_NOTE = @V_NOTE;

		--CLEAN UP
		IF OBJECT_ID('CAPINVREPOSITORY.DBO.TMP_CAPINV_UI_AGG_FREESALE_UBOAT', 'U') IS NOT NULL
		  DROP TABLE CAPINVREPOSITORY.DBO.TMP_CAPINV_UI_AGG_FREESALE_UBOAT;

		IF OBJECT_ID('CAPINVREPOSITORY.DBO.TMP_CAPINV_UI_FREESALE_UBOAT_CURRENT', 'U') IS NOT NULL
		  DROP TABLE CAPINVREPOSITORY.DBO.TMP_CAPINV_UI_FREESALE_UBOAT_CURRENT;

		SET @V_NOTE = @V_PROCESS_NAME + ' COMPLETED SUCCESSFULLY'
		EXEC DBO.USP_LOG_PROCESS @V_PROCESS_ID = @V_PROCESS_ID
							, @V_PROCESS_NAME = @V_PROCESS_NAME
							, @V_USER_NAME = @V_SYSTEM_USER
							, @V_START_DT = NULL
							, @V_END_DT = @V_SYSTEMTIME
							, @V_STATUS = 'COMPLETED'
							, @V_ACTION = 2
							, @V_PARENT_PROCESS_ID = NULL
							, @V_NOTE = @V_NOTE
							, @V_START_STEP = 1;

		SET @V_ERROR_CODE = 0
		RETURN @V_ERROR_CODE
	END TRY
	BEGIN CATCH
		SET @V_MSG = COALESCE(ERROR_PROCEDURE() +' LINE:'+CAST(ERROR_LINE() AS VARCHAR(10))+' MESSAGE:' +ERROR_MESSAGE(),'')
		SET @V_ERRORMESSAGE = 'PROCESS TO REFRESH UBOAT DATA FAILED: ERR:' + @V_MSG
		SET @V_ERRORSEVERITY = ERROR_SEVERITY()  
		SET @V_SYSTEMTIME = GETUTCDATE()
		
		--UPDATE DETAIL 
		EXEC DBO.USP_LOG_PROCESS_DETAIL @V_PROCESS_ID = @V_PROCESS_ID
  					, @V_STEP_ID = @V_STEP_ID
  					, @V_STEP_NAME = @V_STEP_NAME
  					, @V_START_DT = NULL
  					, @V_END_DT = @V_SYSTEMTIME
  					, @V_STATUS = 'FAILED'
  					, @V_ROWS_PROCESSED = NULL
  					, @V_ACTION = 2
  					, @V_NOTE = @V_ERRORMESSAGE
  					;

		--UPDATE PROCESS --COMPLETE PROCESS
		EXEC DBO.USP_LOG_PROCESS @V_PROCESS_ID = @V_PROCESS_ID
							, @V_PROCESS_NAME = @V_PROCESS_NAME
							, @V_USER_NAME = @V_SYSTEM_USER
							, @V_START_DT = NULL
							, @V_END_DT = @V_SYSTEMTIME
							, @V_STATUS = 'FAILED'
							, @V_ACTION = 2
							, @V_PARENT_PROCESS_ID = NULL
							, @V_NOTE =  @V_ERRORMESSAGE
							, @V_START_STEP = 1
							;  

		SET @V_ERROR_CODE = -1
		RETURN @V_ERROR_CODE
	END CATCH
END

