USE [CAPINVREPOSITORY]
GO
/****** OBJECT:  STOREDPROCEDURE [DBO].[USP_CAPFCST_AD_CONSUMPTION]    SCRIPT DATE: 01-08-2017 10:28:37 ******/
IF ( OBJECT_ID('DBO.USP_CAPFCST_AD_CONSUMPTION', 'P') IS NOT NULL ) 
   DROP PROCEDURE DBO.USP_CAPFCST_AD_CONSUMPTION
GO


CREATE PROCEDURE [DBO].[USP_CAPFCST_AD_CONSUMPTION]
/****************************************************************************************************
* COPYRIGHT REVENUE ANALYTICS 2017
* ALL RIGHTS RESERVED
*
* CREATED BY: DATA ENGINEERING
* FILENAME:   USP_CAPFCST_AD_CONSUMPTION.SQL
* DATE:       04/07/2017
*
* APPLICATION:  CREATES ANALYSIS DATA SET FOR CONSUMPTION DATA
*               
* PARAMETERS:   @V_PARENT_PROCESS_ID == PARENT OR CALLING PROCESS ID
*				@V_ERROR_CODE		== RETURNED ERROR CODE
*  				
* ASSUMPTIONS: BOOKING_FINAL, ROUTELINKS AND SCHEDULE TABLES UPDATED
*
* INPUT TABLE(S):	BOOKING_FINAL
*					ROUTELINKS
*					SCHEDULE
* OUTPUT TABLE(S):	CAPFCST_AD_CONSUMPTION
*					CAPFCST_CONSUMPTION_NOREEF
*
* PARAMETERS:   @V_RUNDATE = DATE OF THE RUN
*				@V_SERVICE == SERVICE TO RUN
*				@V_PARENT_PROCESS_ID == PARENT OR CALLING PROCESS ID
*				@V_ERROR_CODE		== RETURNED ERROR CODE
*
* EXAMPLE CALL: DECLARE	@RETURN_VALUE INT,@V_ERROR_CODE INT
*
*				EXEC	@RETURN_VALUE = [DBO].[USP_CAPFCST_AD_CONSUMPTION]
*						@V_RUNDATE = '2017-04-01',
						@V_SERVICE = '84K',
						@V_PARENT_PROCESS_ID = 0,
*						@V_ERROR_CODE = @V_ERROR_CODE OUTPUT
*
*****************************************************************************************************
* NOTES:
*  NAME					CREATED        LAST MOD			COMMENTS
*  DE\ELM               4/17/2017						PROCEDURE CREATED
*  EM									6/26/2017       ADDED CAPABILITY OF RUNNING 13 WEEKS DATA 
														(RUNDATE)          
****************************************************************************************************/
	 @V_RUNDATE DATE
	,@V_SERVICE VARCHAR(10)
	,@V_PARENT_PROCESS_ID INT
	,@V_ERROR_CODE INT OUTPUT
AS
BEGIN
	SET NOCOUNT ON 
	--DECLARE VARIABLES
	DECLARE @V_ERRORMESSAGE NVARCHAR(4000)  
	DECLARE @V_MSG  NVARCHAR(4000)
	DECLARE @V_NOTE  NVARCHAR(4000)
	DECLARE @V_ERRORSEVERITY INT  

	DECLARE @V_PROCESS_ID INT = NEXT VALUE FOR DBO.SEQ_LOG_PROCESS_ID
	DECLARE @V_PROCESS_NAME VARCHAR(255) = OBJECT_SCHEMA_NAME(@@PROCID) + '.' + OBJECT_NAME(@@PROCID)
	DECLARE @V_FIANLERROR INT
	DECLARE @V_SYSTEM_USER NVARCHAR(255) = SYSTEM_USER
	DECLARE @V_SYSTEMTIME DATETIME = GETUTCDATE()
	DECLARE @V_RECORD_CNT INT

	DECLARE @V_STEP_ID TINYINT
	DECLARE @V_STEP_NAME VARCHAR(255)
	DECLARE @V_AUDITVERSIONID INT

	DECLARE @V_FFE_TEU_MULTIPLIER INT = (SELECT CAST(PARAMVALUE AS VARCHAR) FROM ANALYTICSDATAMART.[DBO].[CAPINVUDF_APP_PARAMETER] WHERE UPPER(PARAMNAME) = 'FFE_TO_TEU_MULTIPLIER')
	DECLARE @V_PLUGS_FOR_20 INT = (SELECT CAST(PARAMVALUE AS VARCHAR) FROM ANALYTICSDATAMART.[DBO].[CAPINVUDF_APP_PARAMETER] WHERE UPPER(PARAMNAME) = 'PLUGS_FOR_20')
	DECLARE @V_PLUGS_FOR_40 INT = (SELECT CAST(PARAMVALUE AS VARCHAR) FROM ANALYTICSDATAMART.[DBO].[CAPINVUDF_APP_PARAMETER] WHERE UPPER(PARAMNAME) = 'PLUGS_FOR_40')
	DECLARE @V_IS_VSA_F_FLAG VARCHAR(2) = (SELECT CAST(PARAMVALUE AS VARCHAR) FROM ANALYTICSDATAMART.[DBO].[CAPINVUDF_APP_PARAMETER] WHERE UPPER(PARAMNAME) = 'IS_VSA_F_FLAG')
	DECLARE @V_SHIPMENT_STATUS_FLAG VARCHAR(25) = (SELECT CAST(PARAMVALUE AS VARCHAR) FROM ANALYTICSDATAMART.[DBO].[CAPINVUDF_APP_PARAMETER] WHERE UPPER(PARAMNAME) = 'SHIPMENT_STATUS_FLAG')
	DECLARE @V_LOOKBACK_DAYS INT = (SELECT CAST(PARAMVALUE AS VARCHAR) FROM ANALYTICSDATAMART.[DBO].[CAPINVUDF_APP_PARAMETER] WHERE UPPER(PARAMNAME) = 'LOOKBACK_DAYS')
	DECLARE @V_LOOKFORWARD_DAYS INT = (SELECT CAST(PARAMVALUE AS VARCHAR) FROM ANALYTICSDATAMART.[DBO].[CAPINVUDF_APP_PARAMETER] WHERE UPPER(PARAMNAME) = 'LOOKFORWARD_DAYS')

	--ASSIGN TODAYS DATE IF RUNDATE IS NULL
	SET @V_RUNDATE = CAST(COALESCE(@V_RUNDATE, GETUTCDATE()) AS DATE)
	SET @V_PARENT_PROCESS_ID = COALESCE(@V_PARENT_PROCESS_ID,0)

	BEGIN TRY
		--LOG PROCESS		
		EXEC DBO.USP_LOG_PROCESS @V_PROCESS_ID = @V_PROCESS_ID
							, @V_PROCESS_NAME = @V_PROCESS_NAME
							, @V_USER_NAME = @V_SYSTEM_USER
							, @V_START_DT = @V_SYSTEMTIME
							, @V_END_DT = NULL
							, @V_STATUS = 'RUNNING'
							, @V_ACTION = 1
							, @V_PARENT_PROCESS_ID = @V_PARENT_PROCESS_ID
							, @V_NOTE = 'PROCESS CONSUMPTION DATA'
							, @V_START_STEP = 1;

		SET @V_STEP_ID = 10
		SET @V_STEP_NAME = 'COMBINE BOOKINGS AND ROUTE LINKS'
		SET @V_NOTE = 'COMBINE THE BOOKINGS AND THE SEGMENTS FOR THOSE BOOKINGS FROM THE ROUTELINKS TABLE'
		EXEC DBO.USP_LOG_PROCESS_DETAIL @V_PROCESS_ID = @V_PROCESS_ID
  					, @V_STEP_ID = @V_STEP_ID
  					, @V_STEP_NAME = @V_STEP_NAME
  					, @V_START_DT = @V_SYSTEMTIME
  					, @V_END_DT = NULL
  					, @V_STATUS = 'RUNNING'
  					, @V_ROWS_PROCESSED = NULL
  					, @V_ACTION = 1
  					, @V_NOTE = @V_NOTE;

		IF OBJECT_ID('CAPINVREPOSITORY.DBO.TMPCONSUMPTIONSTEP1', 'U') IS NOT NULL
		  DROP TABLE CAPINVREPOSITORY.DBO.TMPCONSUMPTIONSTEP1;

		SELECT L.[SHIPMENT_NO_X]
			  ,L.[SHIPMENT_VRSN_ID_X]
			  ,L.[BRAND]
			  ,L.[CONTAINER_SIZE_X]
			  ,L.[LOPFI]
			  ,L.[DIPLA]
			  ,L.[POD]
			  ,L.[POR]
			  ,L.[PRICE_CALC_BASE_LCL_D] AS PCD_DATE
			  ,L.[BOOKING_DATE]
			  ,L.[STRING_ID_X]
			  ,L.[ROUTE_CD]
			  ,L.[SHIPMENT_STATUS]
			  ,R.VESSELCODE
			  ,R.SERVICECODE
			  ,R.FROMSITECODE
			  ,R.TOSITECODE
			  ,R.LOCSEQX
			  ,R.DEPVOYAGEX
			  ,R.ARRVOYAGEX
			  ,L.ETD AS ETD
			  , CARGO_TYPE
			  ,SUM(L.[FFE]) AS FFE
			  ,AVG([GROSSWEIGHT]) AS GROSSWEIGHT
		INTO 
			CAPINVREPOSITORY.DBO.TMPCONSUMPTIONSTEP1
		FROM 	
			ANALYTICSDATAMART.[DBO].[BOOKING_FINAL] L (NOLOCK) 
				INNER JOIN ANALYTICSDATAMART.DBO.ROUTELINKS_CLEAN R (NOLOCK)
		ON 
			L.SHIPMENT_NO_X = R.SHIPMENT_NO_X
			AND L.SHIPMENT_VRSN_ID_X = R.SHIPMENT_VRSN_ID_X
		WHERE 	
			UPPER(L.IS_VSA_F) IN (@V_IS_VSA_F_FLAG)
			AND UPPER(L.SHIPMENT_STATUS) IN (@V_SHIPMENT_STATUS_FLAG)
			AND L.ETD BETWEEN DATEADD(DAY, -@V_LOOKBACK_DAYS, @V_RUNDATE) AND DATEADD(DAY, @V_LOOKFORWARD_DAYS,@V_RUNDATE)
			AND (CASE WHEN @V_SERVICE IS NULL OR UPPER(@V_SERVICE) = 'ALL' THEN '1' ELSE R.SERVICECODE END
						= CASE WHEN @V_SERVICE IS NULL OR UPPER(@V_SERVICE) = 'ALL' THEN '1' ELSE @V_SERVICE  END)
		GROUP BY L.[SHIPMENT_NO_X]
			  ,L.[SHIPMENT_VRSN_ID_X]
			  ,L.[BRAND]
			  ,L.[CONTAINER_SIZE_X]
			  ,L.[LOPFI]
			  ,L.[DIPLA]
			  ,L.[POD]
			  ,L.[POR]
			  ,L.[PRICE_CALC_BASE_LCL_D] 
			  ,L.[BOOKING_DATE]
			  ,L.[STRING_ID_X]
			  ,L.[ROUTE_CD]
			  ,L.[SHIPMENT_STATUS]
			  ,R.VESSELCODE
			  ,R.SERVICECODE
			  ,R.FROMSITECODE
			  ,R.TOSITECODE
			  ,R.LOCSEQX
			  ,R.DEPVOYAGEX
			  ,R.ARRVOYAGEX
			  ,L.ETD
			  ,CARGO_TYPE
		OPTION (MAXDOP 8)

		SET @V_RECORD_CNT = @@ROWCOUNT
		SET @V_SYSTEMTIME = GETUTCDATE()
			
		--UPDATE DETAIL 
		SET @V_NOTE = @V_STEP_NAME +' COMPLETELY SUCCESSFULLY'
		EXEC DBO.USP_LOG_PROCESS_DETAIL @V_PROCESS_ID = @V_PROCESS_ID
  					, @V_STEP_ID = @V_STEP_ID
  					, @V_STEP_NAME = @V_STEP_NAME
  					, @V_START_DT = NULL
  					, @V_END_DT = @V_SYSTEMTIME
  					, @V_STATUS = 'COMPLETED'
  					, @V_ROWS_PROCESSED = @V_RECORD_CNT
  					, @V_ACTION = 2
  					, @V_NOTE = @V_NOTE;
		---------------------------------------------------------
		--GET FIRST AND LAST LEG SEQUENCE ID FOR EACH SEGMENT
		---------------------------------------------------------
		SET @V_STEP_ID = 20
		SET @V_STEP_NAME = 'GET THE LEGS INFORMATION FOR THE ROUTE'
		SET @V_NOTE = 'USING THE SCHEDULE GET THE FIRST AND LAST LEG SEQUENCE'
		EXEC DBO.USP_LOG_PROCESS_DETAIL @V_PROCESS_ID = @V_PROCESS_ID
  					, @V_STEP_ID = @V_STEP_ID
  					, @V_STEP_NAME = @V_STEP_NAME
  					, @V_START_DT = @V_SYSTEMTIME
  					, @V_END_DT = NULL
  					, @V_STATUS = 'RUNNING'
  					, @V_ROWS_PROCESSED = NULL
  					, @V_ACTION = 1
  					, @V_NOTE = 'USING THE SCHEDULE GET THE FIRST AND LAST LEG SEQUENCE';



		SELECT DISTINCT A.VESSELCODE
				,A.DEPVOYAGEX AS DEPVOYAGE
				,A.ARRVOYAGEX AS ARRVOYAGE
				,A.SERVICECODE, A.FROMSITECODE
				,MIN(B.SCHEDULEID) OVER (PARTITION BY A.VESSELCODE,A.DEPVOYAGEX, A.SERVICECODE, A.FROMSITECODE) AS FIRSTSCHEDULEID
		INTO #TMP_MIN_SEQ
		FROM CAPINVREPOSITORY.DBO.TMPCONSUMPTIONSTEP1 A
		INNER JOIN ANALYTICSDATAMART.DBO.ROUTELEGS_SCHEDULE B
		ON A.VESSELCODE = B.VESSELCODE
		AND A.DEPVOYAGEX = B.VOYAGE
		AND A.SERVICECODE = B.SERVICECODE
		AND LEFT(A.FROMSITECODE,5) = LEFT(B.DEPARTUREPORT,5)

		SELECT	GG.VESSELCODE
				,GG.DEPVOYAGE
				,GG.SERVICECODE
				,GG.FROMSITECODE
				,A.TOSITECODE
				,GG.FIRSTSCHEDULEID
				,MIN(B.SCHEDULEID) AS LASTSCHEDULEID
		INTO #TMP_ROUTE_SEQ
		FROM DBO.TMPCONSUMPTIONSTEP1 A
		INNER JOIN #TMP_MIN_SEQ GG
		ON A.VESSELCODE = GG.VESSELCODE
		AND A.SERVICECODE = GG.SERVICECODE
		AND (A.DEPVOYAGEX = GG.DEPVOYAGE)
		AND A.FROMSITECODE = GG.FROMSITECODE
		INNER JOIN ANALYTICSDATAMART.DBO.ROUTELEGS_SCHEDULE B
		ON A.VESSELCODE = B.VESSELCODE
		AND A.SERVICECODE = B.SERVICECODE
		AND LEFT(A.TOSITECODE,5) = LEFT(B.ARRIVALPORT,5)
		AND B.SCHEDULEID >= GG.FIRSTSCHEDULEID
		GROUP BY GG.VESSELCODE
				,GG.DEPVOYAGE
				,GG.SERVICECODE
				,GG.FROMSITECODE
				,A.TOSITECODE
				,GG.FIRSTSCHEDULEID

		IF OBJECT_ID('CAPINVREPOSITORY.DBO.TMPCONSUMPTION_LEGS', 'U') IS NOT NULL
			DROP TABLE CAPINVREPOSITORY.DBO.TMPCONSUMPTION_LEGS;

		SELECT 	  L.[SHIPMENT_NO_X]
				  ,L.[SHIPMENT_VRSN_ID_X]
				  ,L.[BRAND]
				  ,L.[CONTAINER_SIZE_X]
				  ,L.[FFE]
				  ,L.CARGO_TYPE
				  ,L.GROSSWEIGHT
				  ,L.[LOPFI]
				  ,L.[DIPLA]
				  ,L.[POD]
				  ,L.[POR]
				  ,L.PCD_DATE
				  ,L.[BOOKING_DATE]
				  ,L.[STRING_ID_X]
				  ,L.[ROUTE_CD]
				  ,L.[SHIPMENT_STATUS]
				  ,L.VESSELCODE
				  ,L.SERVICECODE
				  ,L.FROMSITECODE
				  ,L.TOSITECODE
				  ,L.LOCSEQX
				  ,L.DEPVOYAGEX
				  ,L.ETD
				  ,LL.FIRSTSCHEDULEID
				  ,LL.LASTSCHEDULEID
		INTO CAPINVREPOSITORY.DBO.TMPCONSUMPTION_LEGS
		FROM CAPINVREPOSITORY.DBO.TMPCONSUMPTIONSTEP1 L
		INNER JOIN #TMP_ROUTE_SEQ LL
		ON L.VESSELCODE = LL.VESSELCODE
		AND L.DEPVOYAGEX = LL.DEPVOYAGE
		AND L.SERVICECODE = LL.SERVICECODE
		AND L.FROMSITECODE = LL.FROMSITECODE
		AND L.TOSITECODE = LL.TOSITECODE;

		SET @V_RECORD_CNT = @@ROWCOUNT
		SET @V_SYSTEMTIME = GETUTCDATE()
			
		--UPDATE DETAIL 
		SET @V_NOTE = @V_STEP_NAME +' COMPLETELY SUCCESSFULLY'
		EXEC DBO.USP_LOG_PROCESS_DETAIL @V_PROCESS_ID = @V_PROCESS_ID
  					, @V_STEP_ID = @V_STEP_ID
  					, @V_STEP_NAME = @V_STEP_NAME
  					, @V_START_DT = NULL
  					, @V_END_DT = @V_SYSTEMTIME
  					, @V_STATUS = 'COMPLETED'
  					, @V_ROWS_PROCESSED = @V_RECORD_CNT
  					, @V_ACTION = 2
  					, @V_NOTE = @V_NOTE;

		---------------------------------------------------------
		--ASSIGN LEGS TO EACH SEGMENT
		---------------------------------------------------------
		SET @V_STEP_ID = 25
		SET @V_STEP_NAME = 'ASSIGN LEGS TO EACH SEGMENT'
		SET @V_NOTE = 'USING THE SCHEDULE ASSIGN LEGS TO EACH ROUTE SEGMENTS'
		EXEC DBO.USP_LOG_PROCESS_DETAIL @V_PROCESS_ID = @V_PROCESS_ID
  					, @V_STEP_ID = @V_STEP_ID
  					, @V_STEP_NAME = @V_STEP_NAME
  					, @V_START_DT = @V_SYSTEMTIME
  					, @V_END_DT = NULL
  					, @V_STATUS = 'RUNNING'
  					, @V_ROWS_PROCESSED = NULL
  					, @V_ACTION = 1
  					, @V_NOTE = @V_NOTE;

		IF OBJECT_ID('CAPINVREPOSITORY.DBO.TMPCONSUMPTIONSTEP2', 'U') IS NOT NULL
			DROP TABLE CAPINVREPOSITORY.DBO.TMPCONSUMPTIONSTEP2;

		SELECT  L.[SHIPMENT_NO_X]
				,L.[SHIPMENT_VRSN_ID_X]
				,L.[BRAND]
				,L.[CONTAINER_SIZE_X]
				,L.[FFE]
				,L.CARGO_TYPE
				,L.GROSSWEIGHT
				,L.[LOPFI]
				,L.[DIPLA]
				,L.[POD]
				,L.[POR]
				,L.PCD_DATE
				,L.[BOOKING_DATE]
				,L.[STRING_ID_X]
				,L.[ROUTE_CD]
				,L.[SHIPMENT_STATUS]
				,L.VESSELCODE
				,L.SERVICECODE
				,L.FROMSITECODE
				,L.TOSITECODE
				,L.LOCSEQX
				,R.VOYAGE AS VOYAGE
				,R.ARRVOYAGE
				,L.ETD
				,R.SCHEDULEID
				,R.DEPARTUREPORT
				,R.ARRIVALPORT
				,R.ARRIVALDATE
				,R.LEGSEQID
				,R.[ORIGINAL_ETD]
				,R.[ACTUAL_ETD]
				,R.SERVICECODEDIRECTION
				,R.NEXTDEPVOYAGE
		INTO CAPINVREPOSITORY.DBO.TMPCONSUMPTIONSTEP2
		FROM CAPINVREPOSITORY.DBO.TMPCONSUMPTION_LEGS L 
		INNER JOIN ANALYTICSDATAMART.DBO.ROUTELEGS_SCHEDULE R 
		ON ISNULL(LTRIM(RTRIM(L.SERVICECODE)),0) = ISNULL(LTRIM(RTRIM(R.SERVICECODE)),0)
			AND ISNULL(LTRIM(RTRIM(L.VESSELCODE)),0) = ISNULL(LTRIM(RTRIM(R.VESSELCODE)),0)
				AND R.SCHEDULEID BETWEEN L.FIRSTSCHEDULEID AND L.LASTSCHEDULEID;

		SET @V_RECORD_CNT = @@ROWCOUNT
		SET @V_SYSTEMTIME = GETUTCDATE()
			
		--UPDATE DETAIL 
		SET @V_NOTE = @V_STEP_NAME + ' COMPLETED SUCCESSFULLY'
		EXEC DBO.USP_LOG_PROCESS_DETAIL @V_PROCESS_ID = @V_PROCESS_ID
  					, @V_STEP_ID = @V_STEP_ID
  					, @V_STEP_NAME = @V_STEP_NAME
  					, @V_START_DT = NULL
  					, @V_END_DT = @V_SYSTEMTIME
  					, @V_STATUS = 'COMPLETED'
  					, @V_ROWS_PROCESSED = @V_RECORD_CNT
  					, @V_ACTION = 2
  					, @V_NOTE = @V_NOTE;

		---------------------------------------------------------
		--THIS FINAL STEP INCORPORATES THE FREESALE FLAG BASED ON COMMITMENT DATA
		---------------------------------------------------------
		SET @V_STEP_ID = 40
		SET @V_STEP_NAME = 'BUILD CONSUMPTION ANALYSIS DATA SET'
		SET @V_NOTE = 'ADD THE FREESALE FLAG AND CREATE THE ANALYSIS DATASET'
		EXEC DBO.USP_LOG_PROCESS_DETAIL @V_PROCESS_ID = @V_PROCESS_ID
  					, @V_STEP_ID = @V_STEP_ID
  					, @V_STEP_NAME = @V_STEP_NAME
  					, @V_START_DT = @V_SYSTEMTIME
  					, @V_END_DT = NULL
  					, @V_STATUS = 'RUNNING'
  					, @V_ROWS_PROCESSED = NULL
  					, @V_ACTION = 1
  					, @V_NOTE = @V_NOTE;

		IF OBJECT_ID('CAPINVREPOSITORY.DBO.CAPFCST_AD_CONSUMPTION', 'U') IS NOT NULL
		  DROP TABLE CAPINVREPOSITORY.DBO.CAPFCST_AD_CONSUMPTION;
		  
		SELECT DISTINCT L.SHIPMENT_NO_X
			,L.SHIPMENT_VRSN_ID_X
			,L.BOOKING_DATE
			,L.ROUTE_CD
			,L.SERVICECODE
			,L.STRING_ID_X
			,L.VESSELCODE AS VESSEL
			,L.VOYAGE
			,L.ARRVOYAGE
			,L.LEGSEQID
			,L.SERVICECODEDIRECTION
			,L.CONTAINER_SIZE_X
			,L.CARGO_TYPE
			,L.LOPFI
			,L.DIPLA
			,L.FROMSITECODE
			,L.TOSITECODE
			,L.SCHEDULEID
			,LTRIM(RTRIM(L.DEPARTUREPORT)) AS FROMLEGSITECODE
			,L.ARRIVALPORT AS TOLEGSITECODE
			,COALESCE(L.ORIGINAL_ETD,L.ETD) AS DEPARTUREDATE
			,L.ETD
			,L.ARRIVALDATE
			,L.FFE * @V_FFE_TEU_MULTIPLIER AS TEU
			,L.GROSSWEIGHT
			,CASE WHEN UPPER(L.CARGO_TYPE) = 'REEF' AND L.CONTAINER_SIZE_X = 20 THEN @V_PLUGS_FOR_20
				 WHEN UPPER(L.CARGO_TYPE) = 'REEF' AND L.CONTAINER_SIZE_X = 40 THEN @V_PLUGS_FOR_40
				 ELSE 0
			END AS PLUGS
			,CASE WHEN L.CONTAINER_SIZE_X = 20 THEN FFE * @V_FFE_TEU_MULTIPLIER
				 WHEN L.CONTAINER_SIZE_X = 40 THEN FFE
				 ELSE FFE
			END AS CONTAINERCOUNT
			,CAST(CASE WHEN R.COMMITMENTID IS NOT NULL THEN 0 ELSE 1 END AS TINYINT) AS ISFREESALE
			,NEXTDEPVOYAGE
			,DT.INT_ISO_YEARWEEK
			,DT.CHAR_ISO_YEARWEEK
		INTO 
			CAPINVREPOSITORY.DBO.CAPFCST_AD_CONSUMPTION 
			FROM CAPINVREPOSITORY.DBO.TMPCONSUMPTIONSTEP2 L (NOLOCK)
			INNER JOIN ANALYTICSDATAMART.DBO.DIM_DATE DT
			ON CAST(COALESCE(L.ORIGINAL_ETD,L.ETD) AS DATE) = CAST(DT.DATE AS DATE)
		LEFT OUTER JOIN ANALYTICSDATAMART.DBO.BOOKINGCOMMITMENT R (NOLOCK)
		ON 
			L.SHIPMENT_NO_X = R.SHIPMENT_NO_X
			AND L.CARGO_TYPE = R.CARGO_TYPE
			AND L.CONTAINER_SIZE_X = R.CONTAINER_SIZE_X
		OPTION (MAXDOP 8);

		SET @V_RECORD_CNT = @@ROWCOUNT
		SET @V_SYSTEMTIME = GETUTCDATE()
			
		--UPDATE DETAIL 
		SET @V_NOTE = @V_STEP_NAME + ' COMPLETED SUCCESSFULLY'
		EXEC DBO.USP_LOG_PROCESS_DETAIL @V_PROCESS_ID = @V_PROCESS_ID
  					, @V_STEP_ID = @V_STEP_ID
  					, @V_STEP_NAME = @V_STEP_NAME
  					, @V_START_DT = NULL
  					, @V_END_DT = @V_SYSTEMTIME
  					, @V_STATUS = 'COMPLETED'
  					, @V_ROWS_PROCESSED = @V_RECORD_CNT
  					, @V_ACTION = 2
  					, @V_NOTE = @V_NOTE;

		CREATE CLUSTERED INDEX CDX_CAPFCST_AD_CONSUMPTION ON DBO.CAPFCST_AD_CONSUMPTION(BOOKING_DATE,VESSEL,VOYAGE,SHIPMENT_NO_X,SHIPMENT_VRSN_ID_X, SERVICECODE,LEGSEQID,FROMLEGSITECODE,TOLEGSITECODE,DEPARTUREDATE,ARRIVALDATE)

		SET @V_STEP_ID = 41
		SET @V_STEP_NAME = 'BUILD HISTORICAL STRING TO ROUTE CODE MAP'
		SET @V_NOTE = 'USING HISTORICAL BOOKING, TO BUILD MAPPING BETWEEN ROUTE_CD AND STRING_ID_X'
		EXEC DBO.USP_LOG_PROCESS_DETAIL @V_PROCESS_ID = @V_PROCESS_ID
  					, @V_STEP_ID = @V_STEP_ID
  					, @V_STEP_NAME = @V_STEP_NAME
  					, @V_START_DT = @V_SYSTEMTIME
  					, @V_END_DT = NULL
  					, @V_STATUS = 'RUNNING'
  					, @V_ROWS_PROCESSED = NULL
  					, @V_ACTION = 1
  					, @V_NOTE = @V_NOTE;

			/******************************************************
					BUILD HISTORICAL DISTRIBUTION TABLE
			*******************************************************/
			IF OBJECT_ID('CAPINVREPOSITORY.DBO.TMP_ISC_LIST_AVG', 'U') IS NOT NULL
				DROP TABLE CAPINVREPOSITORY.DBO.TMP_ISC_LIST_AVG;

			SELECT       L.VESSEL
						,L.SERVICECODE
						,L.SERVICECODEDIRECTION
						,FROMLEGSITECODE
						,TOLEGSITECODE
						,DEPARTUREDATE
						,L.INT_ISO_YEARWEEK AS WEEKNO
						,L.VOYAGE
						,L.ARRVOYAGE
						,L.LEGSEQID
						,L.STRING_ID_X
						,L.ROUTE_CD
						,CAST(COALESCE(LD.ISC,'LEAD') AS VARCHAR(8)) AS ISC
						,SUM(TEU) AS TOTALTEU
			INTO CAPINVREPOSITORY.DBO.TMP_ISC_LIST_AVG
			FROM CAPINVREPOSITORY.[DBO].CAPFCST_AD_CONSUMPTION L 
			LEFT JOIN ( 
						SELECT DISTINCT SERVICECODE,SERVICECODEDIRECTION,LEAD_ROUTE AS ROUTE_CD,ISC
						FROM ANALYTICSDATAMART.DBO.DIM_LEAD_ROUTE
						UNION 
						SELECT DISTINCT SERVICECODE,SERVICECODEDIRECTION,CHILD_ROUTE, ISC
						FROM ANALYTICSDATAMART.DBO.DIM_LEAD_ROUTE
					  )LD
			ON L.SERVICECODE = LD.SERVICECODE
			AND L.SERVICECODEDIRECTION = LD.SERVICECODEDIRECTION
			AND L.ROUTE_CD = LD.ROUTE_CD
			WHERE L.ROUTE_CD IS NOT NULL AND L.ROUTE_CD <> ''
			GROUP BY L.VESSEL
						,L.SERVICECODE
						,L.SERVICECODEDIRECTION
						,FROMLEGSITECODE
						,TOLEGSITECODE
						,DEPARTUREDATE
						,L.INT_ISO_YEARWEEK
						,L.VOYAGE
						,L.ARRVOYAGE
						,L.LEGSEQID
						,L.STRING_ID_X
						,L.ROUTE_CD
						,CAST(COALESCE(LD.ISC,'LEAD') AS VARCHAR(8))
			OPTION (MAXDOP 8);

		SET @V_RECORD_CNT = @@ROWCOUNT
		SET @V_SYSTEMTIME = GETUTCDATE()
			
		--UPDATE DETAIL 
		SET @V_NOTE = @V_STEP_NAME + ' COMPLETED SUCCESSFULLY'
		EXEC DBO.USP_LOG_PROCESS_DETAIL @V_PROCESS_ID = @V_PROCESS_ID
  					, @V_STEP_ID = @V_STEP_ID
  					, @V_STEP_NAME = @V_STEP_NAME
  					, @V_START_DT = NULL
  					, @V_END_DT = @V_SYSTEMTIME
  					, @V_STATUS = 'COMPLETED'
  					, @V_ROWS_PROCESSED = @V_RECORD_CNT
  					, @V_ACTION = 2
  					, @V_NOTE = @V_NOTE;

			CREATE CLUSTERED INDEX CDX_DATA_2 ON DBO.TMP_ISC_LIST_AVG(SERVICECODE,ROUTE_CD,STRING_ID_X)

			/******************************************************
					GET ONE TO ONE STRING TO ROUTE_CD
			*******************************************************/
			SET @V_STEP_ID = 42
			SET @V_STEP_NAME = 'GET RECORDS WITH 1 TO 1 MAP BETWEEN STRING CODE AND ROUTE CODE'
			SET @V_NOTE = 'GET RECORDS WITH 1 TO 1 MAP BETWEEN STRING CODE AND ROUTE CODE'
			EXEC DBO.USP_LOG_PROCESS_DETAIL @V_PROCESS_ID = @V_PROCESS_ID
  						, @V_STEP_ID = @V_STEP_ID
  						, @V_STEP_NAME = @V_STEP_NAME
  						, @V_START_DT = @V_SYSTEMTIME
  						, @V_END_DT = NULL
  						, @V_STATUS = 'RUNNING'
  						, @V_ROWS_PROCESSED = NULL
  						, @V_ACTION = 1
  						, @V_NOTE = @V_NOTE;

			IF OBJECT_ID('CAPINVREPOSITORY.DBO.TMP_ISC_LIST_SING', 'U') IS NOT NULL
				DROP TABLE CAPINVREPOSITORY.DBO.TMP_ISC_LIST_SING;

			WITH DUP1_1 AS
			(
				SELECT SERVICECODE,SERVICECODEDIRECTION,STRING_ID_X
				FROM CAPINVREPOSITORY.DBO.TMP_ISC_LIST_AVG
				GROUP BY SERVICECODE,SERVICECODEDIRECTION,STRING_ID_X
				HAVING COUNT(DISTINCT ROUTE_CD) = 1
			)
			SELECT L.VESSEL
					,L.SERVICECODE
					,L.SERVICECODEDIRECTION
					,L.FROMLEGSITECODE
					,L.TOLEGSITECODE
					,L.DEPARTUREDATE
					,L.WEEKNO
					,L.VOYAGE
					,L.ARRVOYAGE
					,L.LEGSEQID
					,L.STRING_ID_X
					,L.ROUTE_CD
					,L.TOTALTEU
					,ISC
					,CAST('1 TO 1' AS VARCHAR(75)) AS ISCREASON
					,CAST(1.0 AS NUMERIC(10,4)) AS TEU_DIST
			INTO CAPINVREPOSITORY.DBO.TMP_ISC_LIST_SING
			FROM CAPINVREPOSITORY.DBO.TMP_ISC_LIST_AVG L
			INNER JOIN DUP1_1 GG
			ON L.SERVICECODE = GG.SERVICECODE
			AND L.SERVICECODEDIRECTION = GG.SERVICECODEDIRECTION
			AND L.STRING_ID_X = GG.STRING_ID_X;

		SET @V_RECORD_CNT = @@ROWCOUNT
		SET @V_SYSTEMTIME = GETUTCDATE()
			
		--UPDATE DETAIL 
		SET @V_NOTE = @V_STEP_NAME + ' COMPLETED SUCCESSFULLY'
		EXEC DBO.USP_LOG_PROCESS_DETAIL @V_PROCESS_ID = @V_PROCESS_ID
  					, @V_STEP_ID = @V_STEP_ID
  					, @V_STEP_NAME = @V_STEP_NAME
  					, @V_START_DT = NULL
  					, @V_END_DT = @V_SYSTEMTIME
  					, @V_STATUS = 'COMPLETED'
  					, @V_ROWS_PROCESSED = @V_RECORD_CNT
  					, @V_ACTION = 2
  					, @V_NOTE = @V_NOTE;

			/******************************************************
					MATCH MULTIPLE ROUTE CODE TO STEERING TABLE
					IF NO MATCHING STEERED ISC, ISC IS PASSIVE 
					AND ALLOCATED TO LEAD ROUTE
			*******************************************************/
			SET @V_STEP_ID = 43
			SET @V_STEP_NAME = 'GET RECORDS WITH MANY TO 1 MAP BETWEEN STRING CODE AND ROUTE CODE'
			SET @V_NOTE = 'GET RECORDS WITH MANY TO 1 MAP BETWEEN STRING CODE AND ROUTE CODE'
			EXEC DBO.USP_LOG_PROCESS_DETAIL @V_PROCESS_ID = @V_PROCESS_ID
  						, @V_STEP_ID = @V_STEP_ID
  						, @V_STEP_NAME = @V_STEP_NAME
  						, @V_START_DT = @V_SYSTEMTIME
  						, @V_END_DT = NULL
  						, @V_STATUS = 'RUNNING'
  						, @V_ROWS_PROCESSED = NULL
  						, @V_ACTION = 1
  						, @V_NOTE = @V_NOTE;

			IF OBJECT_ID('CAPINVREPOSITORY.DBO.TMP_ISC_LIST_FIX_MNT', 'U') IS NOT NULL
				DROP TABLE CAPINVREPOSITORY.DBO.TMP_ISC_LIST_FIX_MNT;

			WITH T1 AS
			(
				SELECT SERVICECODE,SERVICECODEDIRECTION,STRING_ID_X, SUM(TOTALTEU) AS TOTALTEU
				FROM CAPINVREPOSITORY.DBO.TMP_ISC_LIST_AVG
				GROUP BY SERVICECODE,SERVICECODEDIRECTION,STRING_ID_X
				HAVING COUNT(DISTINCT ROUTE_CD) > 1
			)
			SELECT L.VESSEL
					,L.SERVICECODE
					,L.SERVICECODEDIRECTION
					,L.FROMLEGSITECODE
					,L.TOLEGSITECODE
					,L.DEPARTUREDATE
					,L.WEEKNO
					,L.VOYAGE
					,L.ARRVOYAGE
					,L.LEGSEQID
					,L.STRING_ID_X
					,L.ROUTE_CD
					,L.TOTALTEU
					,GG.TOTALTEU AS DED_TOTALTEU
					,L.TOTALTEU / GG.TOTALTEU AS TEU_DIST
					,ISC
					,CAST('1 STRING MULTIPLE ROUTE' AS VARCHAR(75)) AS ISCREASON
			INTO CAPINVREPOSITORY.DBO.TMP_ISC_LIST_FIX_MNT
			FROM CAPINVREPOSITORY.DBO.TMP_ISC_LIST_AVG L
			INNER JOIN T1 GG
			ON L.SERVICECODE = GG.SERVICECODE
			AND L.SERVICECODEDIRECTION = GG.SERVICECODEDIRECTION
			AND L.STRING_ID_X = GG.STRING_ID_X;

		SET @V_RECORD_CNT = @@ROWCOUNT
		SET @V_SYSTEMTIME = GETUTCDATE()
			
		--UPDATE DETAIL 
		SET @V_NOTE = @V_STEP_NAME + ' COMPLETED SUCCESSFULLY'
		EXEC DBO.USP_LOG_PROCESS_DETAIL @V_PROCESS_ID = @V_PROCESS_ID
  					, @V_STEP_ID = @V_STEP_ID
  					, @V_STEP_NAME = @V_STEP_NAME
  					, @V_START_DT = NULL
  					, @V_END_DT = @V_SYSTEMTIME
  					, @V_STATUS = 'COMPLETED'
  					, @V_ROWS_PROCESSED = @V_RECORD_CNT
  					, @V_ACTION = 2
  					, @V_NOTE = @V_NOTE;

			/******************************************************
						BUILD FINAL STRING TO ROUTE CODE
			*******************************************************/
			SET @V_STEP_ID = 44
			SET @V_STEP_NAME = 'COMBINE STRING TO ROUTE CODE -- 1 TO 1'
			SET @V_NOTE = 'COMBINE STRING TO ROUTE CODE -- 1 TO 1'
			EXEC DBO.USP_LOG_PROCESS_DETAIL @V_PROCESS_ID = @V_PROCESS_ID
  						, @V_STEP_ID = @V_STEP_ID
  						, @V_STEP_NAME = @V_STEP_NAME
  						, @V_START_DT = @V_SYSTEMTIME
  						, @V_END_DT = NULL
  						, @V_STATUS = 'RUNNING'
  						, @V_ROWS_PROCESSED = NULL
  						, @V_ACTION = 1
  						, @V_NOTE = @V_NOTE;

			IF OBJECT_ID('CAPINVREPOSITORY.DBO.TMP_ISC_LIST_ALL', 'U') IS NOT NULL
				DROP TABLE CAPINVREPOSITORY.DBO.TMP_ISC_LIST_ALL;

			SELECT DISTINCT L.VESSEL
					,L.SERVICECODE
					,L.SERVICECODEDIRECTION
					,L.FROMLEGSITECODE
					,L.TOLEGSITECODE
					,L.DEPARTUREDATE
					,L.WEEKNO
					,L.VOYAGE
					,L.ARRVOYAGE
					,L.LEGSEQID
					,L.STRING_ID_X
					,L.ROUTE_CD
					,L.TEU_DIST
					,L.ISC
					,L.ISCREASON
			INTO CAPINVREPOSITORY.DBO.TMP_ISC_LIST_ALL
			FROM CAPINVREPOSITORY.DBO.TMP_ISC_LIST_SING L;

		SET @V_RECORD_CNT = @@ROWCOUNT
		SET @V_SYSTEMTIME = GETUTCDATE()
			
		--UPDATE DETAIL 
		SET @V_NOTE = @V_STEP_NAME + ' COMPLETED SUCCESSFULLY'
		EXEC DBO.USP_LOG_PROCESS_DETAIL @V_PROCESS_ID = @V_PROCESS_ID
  					, @V_STEP_ID = @V_STEP_ID
  					, @V_STEP_NAME = @V_STEP_NAME
  					, @V_START_DT = NULL
  					, @V_END_DT = @V_SYSTEMTIME
  					, @V_STATUS = 'COMPLETED'
  					, @V_ROWS_PROCESSED = @V_RECORD_CNT
  					, @V_ACTION = 2
  					, @V_NOTE = @V_NOTE;

			SET @V_STEP_ID = 45
			SET @V_STEP_NAME = 'COMBINE STRING TO ROUTE CODE -- MANY TO 1'
			SET @V_NOTE = 'COMBINE STRING TO ROUTE CODE -- 1 TO 1'
			EXEC DBO.USP_LOG_PROCESS_DETAIL @V_PROCESS_ID = @V_PROCESS_ID
  						, @V_STEP_ID = @V_STEP_ID
  						, @V_STEP_NAME = @V_STEP_NAME
  						, @V_START_DT = @V_SYSTEMTIME
  						, @V_END_DT = NULL
  						, @V_STATUS = 'RUNNING'
  						, @V_ROWS_PROCESSED = NULL
  						, @V_ACTION = 1
  						, @V_NOTE = @V_NOTE;

			--ADD MULTIPLE STRING CODE TO ROUTE CODE
			INSERT INTO CAPINVREPOSITORY.DBO.TMP_ISC_LIST_ALL
			(
				 VESSEL
				,SERVICECODE
				,SERVICECODEDIRECTION
				,FROMLEGSITECODE
				,TOLEGSITECODE
				,DEPARTUREDATE
				,WEEKNO
				,VOYAGE
				,ARRVOYAGE
				,LEGSEQID
				,STRING_ID_X
				,ROUTE_CD
				,TEU_DIST
				,ISC
				,ISCREASON
			)
			SELECT DISTINCT L.VESSEL
					,L.SERVICECODE
					,L.SERVICECODEDIRECTION
					,L.FROMLEGSITECODE
					,L.TOLEGSITECODE
					,L.DEPARTUREDATE
					,L.WEEKNO
					,L.VOYAGE
					,L.ARRVOYAGE
					,L.LEGSEQID
					,L.STRING_ID_X
					,L.ROUTE_CD
					,L.TEU_DIST
					,L.ISC
					,L.ISCREASON
			FROM CAPINVREPOSITORY.DBO.TMP_ISC_LIST_FIX_MNT L
			LEFT JOIN CAPINVREPOSITORY.DBO.TMP_ISC_LIST_ALL GG
			ON L.SERVICECODE = GG.SERVICECODE
			AND L.SERVICECODEDIRECTION = GG.SERVICECODEDIRECTION
			AND L.STRING_ID_X = GG.STRING_ID_X
			WHERE GG.STRING_ID_X IS NULL;

		SET @V_RECORD_CNT = @@ROWCOUNT
		SET @V_SYSTEMTIME = GETUTCDATE()
			
		--UPDATE DETAIL 
		SET @V_NOTE = @V_STEP_NAME + ' COMPLETED SUCCESSFULLY'
		EXEC DBO.USP_LOG_PROCESS_DETAIL @V_PROCESS_ID = @V_PROCESS_ID
  					, @V_STEP_ID = @V_STEP_ID
  					, @V_STEP_NAME = @V_STEP_NAME
  					, @V_START_DT = NULL
  					, @V_END_DT = @V_SYSTEMTIME
  					, @V_STATUS = 'COMPLETED'
  					, @V_ROWS_PROCESSED = @V_RECORD_CNT
  					, @V_ACTION = 2
  					, @V_NOTE = @V_NOTE;

		--UPDATE DETAIL 
		SET @V_NOTE = @V_STEP_NAME + ' COMPLETED SUCCESSFULLY'
		EXEC DBO.USP_LOG_PROCESS_DETAIL @V_PROCESS_ID = @V_PROCESS_ID
  					, @V_STEP_ID = @V_STEP_ID
  					, @V_STEP_NAME = @V_STEP_NAME
  					, @V_START_DT = NULL
  					, @V_END_DT = @V_SYSTEMTIME
  					, @V_STATUS = 'COMPLETED'
  					, @V_ROWS_PROCESSED = @V_RECORD_CNT
  					, @V_ACTION = 2
  					, @V_NOTE = @V_NOTE;

		SELECT  DISTINCT A.SERVICECODE
				,FROMPORT
				,TOPORT
				,WEEKNO,VESSELCODE, VOYAGE
				,B.ARRVOYAGE
				,MIN(B.SCHEDULEID) OVER (PARTITION BY A.SERVICECODE, FROMPORT,WEEKNO,VESSELCODE, VOYAGE) AS FIRSTSCHEDULEID
		INTO #TMP_COMMITTED_MIN
		FROM CAPINVREPOSITORY.[DBO].TMP_ISC_COMMITED_TEU_MTS_PLUGS A
		INNER JOIN ANALYTICSDATAMART.DBO.DIM_DATE DT
		ON A.WEEKNO = DT.INT_ISO_YEARWEEK
		INNER JOIN ANALYTICSDATAMART.DBO.ROUTELEGS_SCHEDULE B (NOLOCK)
		ON A.SERVICECODE = B.SERVICECODE
		AND LEFT(A.FROMPORT,5) = LEFT(B.DEPARTUREPORT,5)
		AND CAST(DT.DATE AS DATE) = CAST(B.ORIGINAL_ETD AS DATE)

		SELECT	GG.SERVICECODE, GG.FROMPORT
				, GG.TOPORT
				,GG.FIRSTSCHEDULEID
				,GG.WEEKNO
				,GG.VESSELCODE, GG.VOYAGE
				,GG.ARRVOYAGE
				,MIN(B.SCHEDULEID)  AS LASTSCHEDULEID
		INTO #TMP_COMMITED_SEQ
		FROM #TMP_COMMITTED_MIN GG
		LEFT JOIN ANALYTICSDATAMART.DBO.DIM_DATE DT
		ON GG.WEEKNO = DT.INT_ISO_YEARWEEK
		INNER JOIN ANALYTICSDATAMART.DBO.ROUTELEGS_SCHEDULE B (NOLOCK)
		ON GG.SERVICECODE = B.SERVICECODE
		AND GG.VESSELCODE = B.VESSELCODE
		AND LEFT(GG.TOPORT,5) = LEFT(B.ARRIVALPORT,5)
		--AND CAST(DT.DATE AS DATE) = CAST(B.ORIGINAL_ETD AS DATE)
		AND B.SCHEDULEID >= GG.FIRSTSCHEDULEID
		GROUP BY GG.SERVICECODE, GG.FROMPORT
				, GG.TOPORT
				,GG.FIRSTSCHEDULEID
				,GG.WEEKNO
				,GG.VESSELCODE, GG.VOYAGE
				,GG.ARRVOYAGE;

		/**********************************************************
				ADD LEGS TO THE ISC ALLOCATION DATA
		***********************************************************/
		IF OBJECT_ID('CAPINVREPOSITORY.DBO.TMP_CAPINV_COMMITED_LEGS', 'U') IS NOT NULL
			DROP TABLE CAPINVREPOSITORY.DBO.TMP_CAPINV_COMMITED_LEGS;

		WITH T1 AS
		(
			SELECT L.*,LL.FIRSTSCHEDULEID,LL.LASTSCHEDULEID, LL.VESSELCODE,LL.VOYAGE, LL.ARRVOYAGE
			FROM CAPINVREPOSITORY.DBO.TMP_ISC_COMMITED_TEU_MTS_PLUGS (NOLOCK)  L
			INNER JOIN #TMP_COMMITED_SEQ LL
			ON L.SERVICECODE = LL.SERVICECODE
			AND L.FROMPORT = LL.FROMPORT
			AND L.TOPORT = LL.TOPORT
			AND L.WEEKNO = LL.WEEKNO
		)
		SELECT DISTINCT 
				L.WEEKNO	
				,L.SERVICECODE	
				,L.SELLINGSTRING	
				,L.BUYINGSTRING	
				,L.BUYINGCOMPANY	
				,L.FROMPORT	
				,L.TOPORT	
				,L.TEU	
				,L.WEIGHTKG
				,L.REEFPLUGS
				,R.VESSELCODE
				,R.VOYAGE
				,R.SCHEDULEID
				,R.DEPARTUREPORT
				,R.ARRIVALPORT
				,R.ARRIVALDATE
				,R.LEGSEQID
				,R.[ORIGINAL_ETD] AS DEPARTUREDATE
				,R.[ACTUAL_ETD]
				,R.SERVICECODEDIRECTION
		INTO CAPINVREPOSITORY.DBO.TMP_CAPINV_COMMITED_LEGS
		FROM T1 L 
		INNER JOIN 
		(
			SELECT DD.*, DT.INT_ISO_YEARWEEK AS ETD_DATE
			FROM ANALYTICSDATAMART.DBO.ROUTELEGS_SCHEDULE DD
			INNER JOIN ANALYTICSDATAMART.DBO.DIM_DATE DT
			ON CAST(DD.ORIGINAL_ETD AS DATE) = CAST(DT.DATE AS DATE)
		) R 
		ON ISNULL(LTRIM(RTRIM(L.SERVICECODE)),0) = ISNULL(LTRIM(RTRIM(R.SERVICECODE)),0)
		AND L.VESSELCODE = R.VESSELCODE
		--AND L.WEEKNO = R.ETD_DATE
		AND R.SCHEDULEID BETWEEN L.FIRSTSCHEDULEID AND L.LASTSCHEDULEID;

		/******************************************************
				APPLY HISTORICAL DISTRIBUTION TO DATA
		******************************************************/
		SET @V_STEP_ID = 46
		SET @V_STEP_NAME = 'BUILD LEGS FOR FBR ALLOCATION DATA'
		SET @V_NOTE = 'BUILD LEGS FOR FBR ALLOCATION DATA'
		EXEC DBO.USP_LOG_PROCESS_DETAIL @V_PROCESS_ID = @V_PROCESS_ID
  					, @V_STEP_ID = @V_STEP_ID
  					, @V_STEP_NAME = @V_STEP_NAME
  					, @V_START_DT = @V_SYSTEMTIME
  					, @V_END_DT = NULL
  					, @V_STATUS = 'RUNNING'
  					, @V_ROWS_PROCESSED = NULL
  					, @V_ACTION = 1
  					, @V_NOTE = @V_NOTE;

		IF OBJECT_ID('CAPINVREPOSITORY.DBO.TMP_ISC_ALLOCATED', 'U') IS NOT NULL
			DROP TABLE CAPINVREPOSITORY.DBO.TMP_ISC_ALLOCATED;

		SELECT A.WEEKNO,A.VESSELCODE AS VESSEL,A.VOYAGE,A.SERVICECODE,A.DEPARTUREPORT
				,A.ARRIVALPORT
				,A.LEGSEQID,A.DEPARTUREDATE, A.ARRIVALDATE
				,A.SERVICECODEDIRECTION,B.ISC
				,SUM(A.TEU * COALESCE(B.TEU_DIST,1)) AS CAL_TEU
				,SUM(A.WEIGHTKG * COALESCE(B.TEU_DIST,1)) AS CAL_WEIGHTKG
				,SUM(A.WEIGHTKG * COALESCE(B.TEU_DIST,1))/1000.0 AS CAL_MTS
				,SUM(A.REEFPLUGS * COALESCE(B.TEU_DIST,1)) AS CAL_REEFPLUGS
		INTO CAPINVREPOSITORY.DBO.TMP_ISC_ALLOCATED
		FROM CAPINVREPOSITORY.DBO.TMP_CAPINV_COMMITED_LEGS A
		INNER JOIN CAPINVREPOSITORY.DBO.TMP_ISC_LIST_ALL B
		ON A.VESSELCODE = B.VESSEL
		AND A.VOYAGE = B.VOYAGE
		AND A.SERVICECODE = B.SERVICECODE
		AND LEFT(A.DEPARTUREPORT,5) = LEFT(B.FROMLEGSITECODE,5)
		AND LEFT(A.ARRIVALPORT,5) = LEFT(B.TOLEGSITECODE,5)
		AND A.BUYINGSTRING = B.STRING_ID_X
		GROUP BY A.WEEKNO,A.VESSELCODE,A.VOYAGE,A.SERVICECODE,A.DEPARTUREPORT
				,A.ARRIVALPORT
				,A.LEGSEQID,A.DEPARTUREDATE, A.ARRIVALDATE
				,A.SERVICECODEDIRECTION,B.ISC

		--UPDATE DETAIL 
		SET @V_NOTE = @V_STEP_NAME + ' COMPLETED SUCCESSFULLY'
		EXEC DBO.USP_LOG_PROCESS_DETAIL @V_PROCESS_ID = @V_PROCESS_ID
  					, @V_STEP_ID = @V_STEP_ID
  					, @V_STEP_NAME = @V_STEP_NAME
  					, @V_START_DT = NULL
  					, @V_END_DT = @V_SYSTEMTIME
  					, @V_STATUS = 'COMPLETED'
  					, @V_ROWS_PROCESSED = @V_RECORD_CNT
  					, @V_ACTION = 2
  					, @V_NOTE = @V_NOTE;

		--UPDATE PROCESS --COMPLETE PROCESS
		SET @V_NOTE = @V_PROCESS_NAME + ' COMPLETED SUCCESSFULLY'
		EXEC DBO.USP_LOG_PROCESS @V_PROCESS_ID = @V_PROCESS_ID
							, @V_PROCESS_NAME = @V_PROCESS_NAME
							, @V_USER_NAME = @V_SYSTEM_USER
							, @V_START_DT = NULL
							, @V_END_DT = @V_SYSTEMTIME
							, @V_STATUS = 'COMPLETED'
							, @V_ACTION = 2
							, @V_PARENT_PROCESS_ID = NULL
							, @V_NOTE = @V_NOTE
							, @V_START_STEP = 1;

			SET @V_ERROR_CODE = 0
			RETURN @V_ERROR_CODE
	END TRY
	BEGIN CATCH
		SET @V_MSG = COALESCE(ERROR_PROCEDURE() +' LINE:'+CAST(ERROR_LINE() AS VARCHAR(10))+' MESSAGE:' +ERROR_MESSAGE(),'')
		SET @V_ERRORMESSAGE = 'PROCESS TO REFRESH BOOKING FINAL FAILED: ERR:' + @V_MSG
		SET @V_ERRORSEVERITY = ERROR_SEVERITY()  
		SET @V_SYSTEMTIME = GETUTCDATE()
		
		--UPDATE DETAIL 
		EXEC DBO.USP_LOG_PROCESS_DETAIL @V_PROCESS_ID = @V_PROCESS_ID
  					, @V_STEP_ID = @V_STEP_ID
  					, @V_STEP_NAME = @V_STEP_NAME
  					, @V_START_DT = NULL
  					, @V_END_DT = @V_SYSTEMTIME
  					, @V_STATUS = 'FAILED'
  					, @V_ROWS_PROCESSED = NULL
  					, @V_ACTION = 2
  					, @V_NOTE = @V_ERRORMESSAGE
  					;

		--UPDATE PROCESS --COMPLETE PROCESS
		EXEC DBO.USP_LOG_PROCESS @V_PROCESS_ID = @V_PROCESS_ID
							, @V_PROCESS_NAME = @V_PROCESS_NAME
							, @V_USER_NAME = @V_SYSTEM_USER
							, @V_START_DT = NULL
							, @V_END_DT = @V_SYSTEMTIME
							, @V_STATUS = 'FAILED'
							, @V_ACTION = 2
							, @V_PARENT_PROCESS_ID = NULL
							, @V_NOTE =  @V_ERRORMESSAGE
							, @V_START_STEP = 1
							;  

		SET @V_ERROR_CODE = -1
		RETURN @V_ERROR_CODE
	END CATCH
END
