CREATE PROCEDURE [DBO].[USP_CAPFCST_RUN_FCST]
/****************************************************************************************************
* COPYRIGHT REVENUE ANALYTICS 2017
* ALL RIGHTS RESERVED
*
* CREATED BY: DATA ENGINEERING
* FILENAME:   USP_CAPFCST_AD_CONSUMPTION.SQL
* DATE:       08/01/2017
*
* APPLICATION:  RUNS THE CAPACITY FORECAST
*               
* PARAMETERS:   @V_PARENT_PROCESS_ID == PARENT OR CALLING PROCESS ID
*				@V_ERROR_CODE		== RETURNED ERROR CODE
*  				
* ASSUMPTIONS: BOOKING_FINAL, ROUTELINKS AND SCHEDULE TABLES UPDATED
*
* INPUT TABLE(S):	BOOKING_FINAL
*					ROUTELINKS
*					SCHEDULE
* OUTPUT TABLE(S):	CAPFCST_AD_CONSUMPTION
*					CAPFCST_CONSUMPTION_NOREEF
*
* PARAMETERS:   @V_RUNDATE = DATE OF THE RUN
*				@V_PARENT_PROCESS_ID == PARENT OR CALLING PROCESS ID
*				@V_ERROR_CODE		== RETURNED ERROR CODE
*
* EXAMPLE CALL: DECLARE	@RETURN_VALUE INT,@V_ERROR_CODE INT
*
*				EXEC	@RETURN_VALUE = [DBO].[USP_CAPFCST_RUN_FCST]
*						@V_RUNDATE = '2017-04-01',
						@V_SERVICE = '84K',
*						@V_ERROR_CODE = @V_ERROR_CODE OUTPUT
*
*****************************************************************************************************
* NOTES:
*  NAME					CREATED        LAST MOD			COMMENTS
*  DE\ELM               4/17/2017						PROCEDURE CREATED
*  EM									6/26/2017       ADDED CAPABILITY OF RUNNING 13 WEEKS DATA 
														(RUNDATE)          
****************************************************************************************************/
	 @V_RUNDATE DATE = NULL
	 ,@V_SERVICE VARCHAR(10)
	,@V_PARENT_PROCESS_ID INT = 0
	,@V_ERROR_CODE INT OUTPUT
AS
BEGIN
	SET NOCOUNT ON 
	--DECLARE VARIABLES
	DECLARE @V_ERRORMESSAGE NVARCHAR(4000)  
	DECLARE @V_MSG  NVARCHAR(4000)
	DECLARE @V_NOTE  NVARCHAR(4000)
	DECLARE @V_ERRORSEVERITY INT  

	DECLARE @V_PROCESS_ID INT = NEXT VALUE FOR DBO.SEQ_LOG_PROCESS_ID
	DECLARE @V_PROCESS_NAME VARCHAR(255) = OBJECT_SCHEMA_NAME(@@PROCID) + '.' + OBJECT_NAME(@@PROCID)
	DECLARE @V_FIANLERROR INT
	DECLARE @V_SYSTEM_USER NVARCHAR(255) = SYSTEM_USER
	DECLARE @V_SYSTEMTIME DATETIME = GETUTCDATE()
	DECLARE @V_RECORD_CNT INT

	DECLARE @V_STEP_ID TINYINT
	DECLARE @V_STEP_NAME VARCHAR(255)
	DECLARE @V_AUDITVERSIONID INT
	DECLARE @RETURN_VALUE INT

	EXEC	@RETURN_VALUE = [DBO].[USP_CAPFCST_AD_CONSUMPTION]
						@V_RUNDATE = @V_RUNDATE,
						@V_SERVICE = @V_SERVICE,
						@V_ERROR_CODE = @V_ERROR_CODE OUTPUT
	
	EXEC	@RETURN_VALUE = [DBO].USP_CAPFCST_CALC_FREESALECONSUMPTION
						@V_RUNDATE = @V_RUNDATE,
						@V_ERROR_CODE = @V_ERROR_CODE OUTPUT

END
