use analyticsdatamart
go

IF OBJECT_ID('DBO.[vw_AD_CAPFCST_FREESALE_UBOAT]', 'V') IS NOT NULL
	DROP VIEW DBO.vw_AD_CAPFCST_FREESALE_UBOAT;
GO

create view dbo.vw_AD_CAPFCST_FREESALE_UBOAT as 
WITH UI_AGG_DATA AS
		(
			SELECT      [RUNID]
					   ,[RUNDATE]
					   ,[VOYAGE]
					   ,[VESSELCODE]
					   ,[SERVICECODE]
					   ,[LEGSEQID]
					   ,[SERVICECODEDIRECTION]
					   ,[DEPARTUREPORT]
					   ,[ARRIVALPORT]
					   ,[VESSELOPERATOR]
					   ,MAX([DEPARTUREDATE]) as [DEPARTUREDATE]
					   ,MAX([ARRIVALDATE]) AS [ARRIVALDATE]
					   ,isnull(SUM([INTAKETEU]),0) AS [INTAKETEU]
					   ,isnull(SUM([INTAKETONS]),0) AS [INTAKETONS]
					   ,isnull(SUM([INTAKEPLUGS]),0) AS [INTAKEPLUGS]
					   ,isnull(SUM([ALLOCATIONTEU]),0) AS [ALLOCATIONTEU]
					   ,isnull(SUM([ALLOCATIONTONS]),0) AS [ALLOCATIONTONS]
					   ,isnull(SUM([ALLOCATIONPLUGS]),0) AS [ALLOCATIONPLUGS]
					   ,isnull(SUM([TOTALEMPTYTEU]),0) AS [TOTALEMPTYTEU]
					   ,isnull(SUM([TOTALCOMMITFILINGSTEU]),0) AS [TOTALCOMMITFILINGSTEU]
					   ,isnull(SUM(TOTALCOMMITCONSUMPTIONTEU),0) AS TOTALCOMMITCONSUMPTIONTEU
					   ,isnull(SUM([FREESALEALLOCATIONTEU]),0) AS [FREESALEALLOCATIONTEU]
					   ,isnull(SUM([OVERBOOKTEU]),0) AS [OVERBOOKTEU]
					   ,isnull(CAST(0 AS NUMERIC(15,4)),0) AS OVERBOOKPCT
					   ,isnull(SUM([FREESALE_AVAILABLETEU]),0) AS [FREESALE_AVAILABLETEU]
					   ,isnull(SUM([FREESALECONSUMPTIONTEU]),0) AS [FREESALECONSUMPTIONTEU]
					   ,isnull(SUM([FREESALEDISPLACEMENTTEU]),0) AS [FREESALEDISPLACEMENTTEU]
					   ,isnull(SUM([DISPLACEMENTFFE]),0) AS [DISPLACEMENTFFE]
					   ,isnull(SUM([CONSUMPTIONDISPLACEMENTTEU]),0) AS [CONSUMPTIONDISPLACEMENTTEU]
					   ,isnull(SUM([REMAINING_FREESALEDISPLACEMENTTEU]),0) AS [REMAINING_FREESALEDISPLACEMENTTEU]
					   ,isnull(SUM([REMAINING_FREESALETEU]),0) AS [REMAINING_FREESALETEU]
					   ,isnull(SUM([REMAINING_FREESALEDISPLACEMENTNOOVERBOOKTEU]),0) AS [REMAINING_FREESALEDISPLACEMENTNOOVERBOOKTEU]
					   ,isnull(SUM([REMAINING_FREESALENOOVERBOOKTEU]),0) AS [REMAINING_FREESALENOOVERBOOKTEU]
					   ,isnull(SUM([REMAINING_FREESALEDISPLACEMENTFFE]),0) AS [REMAINING_FREESALEDISPLACEMENTFFE]
					   ,isnull(SUM([REMAINING_FREESALEFFE]),0) AS [REMAINING_FREESALEFFE]
					   ,isnull(SUM([TOTALEMPTYTONS]),0) AS [TOTALEMPTYTONS]
					   ,isnull(SUM([TOTALCOMMITFILINGSTONS]),0) AS [TOTALCOMMITFILINGSTONS]
					   ,isnull(SUM(TOTALCOMMITCONSUMPTIONTONS),0) AS TOTALCOMMITCONSUMPTIONTONS
					   ,isnull(SUM([FREESALEALLOCATIONTONS]),0) AS [FREESALEALLOCATIONTONS]
					   ,isnull(SUM([OVERBOOKTONS]),0) AS [OVERBOOKTONS]
					   ,isnull(SUM([FREESALE_AVAILABLETONS]),0) AS [FREESALE_AVAILABLETONS]
					   ,isnull(SUM([FREESALE_AVAILABLENOOVERBOOKTONS]),0) AS [FREESALE_AVAILABLENOOVERBOOKTONS]
					   ,isnull(SUM([FREESALECONSUMPTIONTONS]),0) AS [FREESALECONSUMPTIONTONS]
					   ,isnull(SUM([REMAINING_FREESALETONS]),0) AS [REMAINING_FREESALETONS]
					   ,isnull(SUM([REMAINING_FREESALENOOVERBOOKTONS]),0) AS [REMAINING_FREESALENOOVERBOOKTONS]
					   ,isnull(SUM([TOTALCOMMITFILINGSPLUGS]),0) AS [TOTALCOMMITFILINGSPLUGS]
					   ,isnull(SUM(TOTALCOMMITCONSUMPTIONPLUGS),0) AS TOTALCOMMITCONSUMPTIONPLUGS
					   ,isnull(SUM([FREESALEALLOCATIONPLUGS]),0) AS [FREESALEALLOCATIONPLUGS]
					   ,isnull(SUM([OVERBOOKPLUGS]),0) AS [OVERBOOKPLUGS]
					   ,isnull(SUM([FREESALE_AVAILABLEPLUGS]),0) AS [FREESALE_AVAILABLEPLUGS]
					   ,isnull(SUM([FREESALE_AVAILABLENOOVERBOOKPLUGS]),0) AS [FREESALE_AVAILABLENOOVERBOOKPLUGS]
					   ,isnull(SUM([FREESALECONSUMPTIONPLUGS]),0) AS [FREESALECONSUMPTIONPLUGS]
					   ,isnull(SUM([REMAINING_FREESALEPLUGS]),0) AS [REMAINING_FREESALEPLUGS]
					   ,isnull(SUM([REMAINING_FREESALENOOVERBOOKPLUGS]),0) AS [REMAINING_FREESALENOOVERBOOKPLUGS]
					   ,CAST('LEAD' AS VARCHAR(10)) AS [ISC]
			FROM ANALYTICSDATAMART.DBO.AD_CAPFCST_FREESALE_UBOAT (NOLOCK)
			GROUP BY [RUNID]
					   ,[RUNDATE]
					   ,[VOYAGE]
					   ,[VESSELCODE]
					   ,[SERVICECODE]
					   ,[LEGSEQID]
					   ,[SERVICECODEDIRECTION]
					   ,[DEPARTUREPORT]
					   ,[ARRIVALPORT]
					   ,[VESSELOPERATOR]
		),
		SUMDATA AS
		(
			SELECT ROW_NUMBER() OVER(ORDER BY VOYAGE) AS ID
					   ,[RUNID]
					   ,datediff(day,rundate,DEPARTUREDATE) as daystodeparture
					   ,[RUNDATE]
					   ,[VOYAGE]
					   ,[VESSELCODE]
					   ,[SERVICECODE]
					   ,[LEGSEQID]
					   ,[SERVICECODEDIRECTION]
					   ,[DEPARTUREPORT]
					   ,[ARRIVALPORT]
					   ,[VESSELOPERATOR]
					   ,[DEPARTUREDATE]
					   ,[ARRIVALDATE]
					   ,[INTAKETEU]
					   ,[INTAKETONS]
					   ,[INTAKEPLUGS]
					   ,[ALLOCATIONTEU]
					   ,[ALLOCATIONTONS]
					   ,[ALLOCATIONPLUGS]
					   ,[TOTALEMPTYTEU]
					   ,[TOTALCOMMITFILINGSTEU]
					   ,TOTALCOMMITCONSUMPTIONTEU
					   ,[FREESALEALLOCATIONTEU]
					   ,analyticsdatamart.dbo.udf_greatest([OVERBOOKTEU],0) as [OVERBOOKTEU]
					   ,OVERBOOKPCT
					   ,[FREESALE_AVAILABLETEU]
					   ,[FREESALECONSUMPTIONTEU]
					   ,[FREESALEDISPLACEMENTTEU]
					   ,[DISPLACEMENTFFE]
					   ,[CONSUMPTIONDISPLACEMENTTEU]
					   ,[REMAINING_FREESALEDISPLACEMENTTEU]
					   ,[REMAINING_FREESALETEU]
					   ,[REMAINING_FREESALEDISPLACEMENTNOOVERBOOKTEU]
					   ,[REMAINING_FREESALENOOVERBOOKTEU]
					   ,[REMAINING_FREESALEDISPLACEMENTFFE]
					   ,[REMAINING_FREESALEFFE]
					   ,[TOTALEMPTYTONS]
					   ,[TOTALCOMMITFILINGSTONS]
					   ,TOTALCOMMITCONSUMPTIONTONS
					   ,[FREESALEALLOCATIONTONS]
					   ,analyticsdatamart.dbo.udf_greatest([OVERBOOKTONS],0) AS [OVERBOOKTONS]
					   ,[FREESALE_AVAILABLETONS]
					   ,[FREESALE_AVAILABLENOOVERBOOKTONS]
					   ,[FREESALECONSUMPTIONTONS]
					   ,[REMAINING_FREESALETONS]
					   ,[REMAINING_FREESALENOOVERBOOKTONS]
					   ,[TOTALCOMMITFILINGSPLUGS]
					   ,TOTALCOMMITCONSUMPTIONPLUGS
					   ,[FREESALEALLOCATIONPLUGS]
					   ,analyticsdatamart.dbo.udf_greatest([OVERBOOKPLUGS],0) AS [OVERBOOKPLUGS]
					   ,[FREESALE_AVAILABLEPLUGS]
					   ,[FREESALE_AVAILABLENOOVERBOOKPLUGS]
					   ,[FREESALECONSUMPTIONPLUGS]
					   ,[REMAINING_FREESALEPLUGS]
					   ,[REMAINING_FREESALENOOVERBOOKPLUGS]
					   ,[ISC]
				FROM UI_AGG_DATA
		)
		SELECT
				   A.ID, A.RUNID,A.daystodeparture, A.RUNDATE, A.VESSELCODE AS VESSEL,A.VOYAGE, A.SERVICECODE AS SERVICE, A.SERVICECODEDIRECTION AS [SERVICE CODE DIRECTION],
				LEFT(A.DEPARTUREPORT, 5) AS [DEPARTURE PORTCALL],PC1.SITENAME AS [DEPARTURE PORTCITY], LEFT(A.ARRIVALPORT, 5) AS [ARRIVAL PORTCALL],PC2.SITENAME AS [ARRIVAL PORTCITY],
					  A.LEGSEQID, CAST(A.DEPARTUREDATE AS DATE) AS DEPARTURE, DT.INT_YEARWEEK AS WEEK_OF_YEAR,
				CAST(A.ARRIVALDATE AS DATE) AS ARRIVAL, A.ALLOCATIONTEU AS [MSK ALLOCATION TEU], A.ALLOCATIONTONS AS [MSK ALLOCATION MTS],
				A.ALLOCATIONPLUGS AS [MSK ALLOCATION PLUGS], CAST(ROUND(A.TOTALEMPTYTEU, 0) AS INT) AS [EMPTY ALLOCATION TEU], CAST(ROUND(A.TOTALEMPTYTONS, 0) AS INT)
				AS [EMPTY ALLOCATION MTS]
				, CAST(A.TOTALCOMMITFILINGSTEU AS INT) AS [COMMITMENT ALLOCATION TEU]
				, CAST(ROUND(A.TOTALCOMMITFILINGSTONS, 0) AS INT) AS [COMMITMENT ALLOCATION MTS]
				, CAST(A.TOTALCOMMITFILINGSPLUGS AS INT) AS [COMMITMENT ALLOCATION PLUGS]
				, CAST(A.TOTALCOMMITCONSUMPTIONTEU AS INT)	AS [COMMITMENT CONSUMPTION TEU]
				, CAST(ROUND(A.TOTALCOMMITCONSUMPTIONTONS, 0) AS INT) AS [COMMITMENT CONSUMPTION MTS]
				, CAST(A.TOTALCOMMITCONSUMPTIONPLUGS AS INT) AS [COMMITMENT CONSUMPTION PLUGS]
				, CAST(A.FREESALEALLOCATIONTEU AS INT) AS [FREESALE AVAILABLE TEU - BEFORE OVERBOOKING]
				, CAST(ROUND(A.FREESALE_AVAILABLENOOVERBOOKTONS, 0) AS INT) AS [FREESALE AVAILABLE MTS - BEFORE OVERBOOKING], CAST(A.FREESALE_AVAILABLENOOVERBOOKPLUGS AS INT)
				AS [FREESALE AVAILABLE PLUGS - BEFORE OVERBOOKING], CAST(A.FREESALE_AVAILABLETEU AS INT) AS [FREESALE AVAILABLE TEU - INCL.  OVERBOOKING],
				CAST(ROUND(A.FREESALE_AVAILABLETONS, 0) AS INT) AS [FREESALE AVAILABLE MTS - INCL.  OVERBOOKING], CAST(A.FREESALE_AVAILABLEPLUGS AS INT)
				AS [FREESALE AVAILABLE PLUGS - INCL.  OVERBOOKING], CAST(A.FREESALECONSUMPTIONTEU AS INT) AS [FREESALE CONSUMPTION TEU], CAST(A.FREESALEDISPLACEMENTTEU AS INT)
				AS [OOG DISPLACEMENT TEU], CAST(A.CONSUMPTIONDISPLACEMENTTEU AS INT) AS [FREESALE CONSUMPTION AND DISPLACEMENT TEU TOTAL],
				CAST(ROUND(A.FREESALECONSUMPTIONTONS, 0) AS INT) AS [FREESALE CONSUMPTION MTS], CAST(A.FREESALECONSUMPTIONPLUGS AS INT) AS [FREESALE CONSUMPTION PLUGS],
				CAST(A.REMAINING_FREESALETEU AS INT) AS [REMAINING CAPACITY TEU - BEFORE OOG DISPLACEMENT], CAST(A.REMAINING_FREESALEDISPLACEMENTTEU AS INT)
				AS [REMAINING CAPACITY TEU - INCL. OOG DISPLACEMENT], CAST(ROUND(A.REMAINING_FREESALETONS, 0) AS INT) AS [REMAINING CAPACITY MTS],
				CAST(A.REMAINING_FREESALEPLUGS AS INT) AS [REMAINING CAPACITY PLUGS], ISC AS [ISC INDICATOR (LEAD TRADE / ISC1)],
				SVC.SERVICENAME, VSL.VESSELNAME
		FROM   SUMDATA A
			   INNER JOIN  ANALYTICSDATAMART.DBO.DIM_DATE AS DT (NOLOCK)
		ON
			   CAST(A.DEPARTUREDATE AS DATE) = CAST(DT.DATE AS DATE)
		INNER JOIN ANALYTICSDATAMART.DBO.DIM_SERVICE SVC (NOLOCK)
		ON
			   A.SERVICECODE = SVC.SERVICECD
		LEFT OUTER JOIN ANALYTICSDATAMART.DBO.VWVESSELS VSL
		ON
			   A.VESSELCODE = VSL.VESSELCODE
		LEFT OUTER JOIN ANALYTICSDATAMART.DBO.VWPORTCITIES PC1
		ON
			   A.DEPARTUREPORT = PC1.SITE_CD
		LEFT OUTER JOIN ANALYTICSDATAMART.DBO.VWPORTCITIES PC2
		ON
			   A.ARRIVALPORT = PC2.SITE_CD
		WHERE
			   LEFT(A.DEPARTUREPORT, 5) <> LEFT(A.ARRIVALPORT,5) AND A.SERVICECODEDIRECTION IS NOT NULL;
